### ISSUE TITLE
Include a folder of compatibility .inis with TheXTech for known episodes that require them

### ISSUE THREAD

**Issue by P-Star7** [TheXTech/TheXTech#104]
For example, ASMBXT.ini that has multipoints disabled. This is so that the user will know that they need this to play this episode and also does not need to find out what correct settings that they need. The player will rename it to compat.ini and place it in the episode's folder if they download that episode.

**Comment by DerpyBubblez** [comment]
https://github.com/Wohlstand/TheXTech/issues/54

**Comment by Wohlstand** [comment]
It's already an exact plan to implement the global compatibility list where you will be able to specify which episodes or single levels will have an enforced compatibility setup.

**Comment by Wohlstand** [comment]
Closed as duplicate for #54
