### ISSUE TITLE
Feature Request: sounds.ini Flag For 'sound-9' instead of 'sound-2' on stomp

### ISSUE THREAD

**Issue by ChristianSilvermoon** [TheXTech/TheXTech#107]
For SMW style stomping sound effects, using `sound-9` "Shell Kick" as opposed to `sound-2` "Stomp" when landing on an enemy that will die from the attack.

`sound-2` should still be used for stomping bosses, other players, and for enemies that don't die from being jumped on (IE spin jumping on thwomps and grinders, or enemies that you simply bounce off of when jumping on like Chargin' Chucks in M&L's Delightful Adventure).

If possible, with this flag is enabled, when consecutively stomping enemies the sound's pitch should increase with the score received.

**Comment by ds-sloth** [comment]
I don't think it's in-scope for the project for us to change the sound effect used for certain enemies, but I think that an option to shift the pitch (of either sound-9 or sound-2) according to the active score multiplier would be really fun. It might require some small additions to MixerX.

**Comment by ChristianSilvermoon** [comment]
> I don't think it's in-scope for the project for us to change the sound effect used for certain enemies, but I think that an option to shift the pitch (of either sound-9 or sound-2) according to the active score multiplier would be really fun. It might require some small additions to MixerX.

As the project and its goals have evolved I am somewhat inclined to agree
