### ISSUE TITLE
Bug: Volcano Lotus Isn't Harmed By Bashing The Block Beneath It

### ISSUE THREAD

**Issue by ChristianSilvermoon** [TheXTech/TheXTech#109]
**Describe the bug**
The *Volcano Lotus* cannot be harmed by hitting the block it is on

**Example Case**

[Volcano Lotus Bug Test.lvl.zip](https://github.com/Wohlstand/TheXTech/files/6508139/Volcano.Lotus.Bug.Test.lvl.zip)

**Recording**

![Scr_2021-05-19_03-52-51](https://user-images.githubusercontent.com/30162808/118801585-08d7f100-b856-11eb-8072-b80d9ca967a1.gif)

**Vanilla Recording**

![image](https://user-images.githubusercontent.com/30162808/118804126-23f83000-b859-11eb-9d4a-c72a5d9574be.png)
(Behaviour is consistent)

**Additional context**

*N/a*

**Comment by P-Star7** [comment]
This is an inaccuracy to Super Mario World, and may confuse new SMBX players. See here for an NPC code idea that determines if the NPC can be killed by bumping the block.
https://github.com/Wohlstand/TheXTech/issues/117

**Comment by ChristianSilvermoon** [comment]
> This is an inaccuracy to Super Mario World, and may confuse new SMBX players, which is why ChristianSilvermoon calls it "bug". See here for an NPC code idea that determines if the NPC can be killed by bumping the block.
> #117

I call it a bug because it violates the logical precedent set by most 2D Mario games in general. It's fairly unusual for an enemy to be immune to being hit by the block beneath them.

**Comment by ds-sloth** [comment]
This is a balance change that we won't make.
