### ISSUE TITLE
Boos Seem To Be Unpredictable in Multiplayer

### ISSUE THREAD

**Issue by ChristianSilvermoon** [TheXTech/TheXTech#120]
While playing Super Talking Time Bros with my husband, we realized that boos seem to behave... strangely.

Perhaps they should target the closest player? I'm not sure how they decided who to target here

Instance clipped on Twitch:
https://clips.twitch.tv/CrunchyBlitheDeerPicoMause-0P23x-kKtZNA2VwS

**Comment by Wohlstand** [comment]
That happens because of the silly logic that detects players. It should do one of next:
- React on the nearest player only (find the shortest distance, and choose that player for the check)
- React when both players not watching the boo, but if one of them keeps an eye, don't act

what whay you think is better?

**Comment by ChristianSilvermoon** [comment]
They're both good, but the first one I feel renders them slightly more dangerous

The second one ties well into the logic that boos are shy, however

**Comment by ChristianSilvermoon** [comment]
I'd go with closest player for it to keep things more interesting

**Comment by 0lhi** [comment]
I prefer the second approach. It seems to apply to NSMBWii, too:

https://youtu.be/qw7E-6cWRnE?t=42

**Comment by ChristianSilvermoon** [comment]
> I prefer the second approach. It seems to apply to NSMBWii, too:
> 
> https://youtu.be/qw7E-6cWRnE?t=42
> 
> ![GhostHouses](https://user-images.githubusercontent.com/74732674/120200236-63912580-c224-11eb-8b94-28b9fe78db7b.png)

I mean both work really well, only point I really have for the first one is it makes boos a little more dangerous in co-op, since the NSMB Wii approach basically means one player could stand on one side of the room and look at them and they won't move while the other plays through the platforming, then waits for the other player to come across the room while looking at all the boos. Effectively meaning co-op play can render them not much of a threat.

**Comment by ds-sloth** [comment]
From a quick read of the code, this is happening because Ghosts target the NPC closest to them based on the X axis only. This is appropriate for many NPCs (the flying enemies that throw NPCs, for instance), but I don't know whether it's appropriate for Ghosts.

Should we change the code to target the nearest player instead? I'm already planning a compat flag covering a number of updates to multiplayer targeting.

**Comment by ChristianSilvermoon** [comment]
> From a quick read of the code, this is happening because Ghosts target the NPC closest to them based on the X axis only. This is appropriate for many NPCs (the flying enemies that throw NPCs, for instance), but I don't know whether it's appropriate for Ghosts.
> 
> Should we change the code to target the nearest player instead? I'm already planning a compat flag covering a number of updates to multiplayer targeting.

I'm for targeting nearest, personally

**Comment by ds-sloth** [comment]
This should be fixed now. Krissy, can you please test on your side? Note that many other NPCs were also fixed in the same way (squids, several bosses, item throwers, etc). I think this will be very useful for cases where multiple players are in vertically tall sections.

**Comment by ChristianSilvermoon** [comment]
> This should be fixed now. Krissy, can you please test on your side? Note that many other NPCs were also fixed in the same way (squids, several bosses, item throwers, etc). I think this will be very useful for cases where multiple players are in vertically tall sections.

The Boos themselves definitely behave consistently now ^^

**Comment by ds-sloth** [comment]
Great, thanks for the confirmation!
