### ISSUE TITLE
Bug: NPC-195 "Rainbow Shell" Can Cause Softlocks By Trapping Them In The Lifting Animation

### ISSUE THREAD

**Issue by ChristianSilvermoon** [TheXTech/TheXTech#125]
**Describe the bug**
When trying to dig up Block-370 (Diggable Sand), if a moving NPC-195 (Rainbow Shell) collides with the player, the player is trapped in the lifting animation and cannot move.

Additionally, if lifting NPC-91 (Grass Container), the player will briefly turn invisible.

**Example Case**
[NPC-195 Rainbow Shell Softlock Bug Test.lvl.zip](https://github.com/Wohlstand/TheXTech/files/6565622/NPC-195.Rainbow.Shell.Softlock.Bug.Test.lvl.zip)

**Recording**
![Scr_2021-05-29_19-40-09](https://user-images.githubusercontent.com/30162808/120090333-75ed5100-c0b6-11eb-8470-2b061770adaf.gif)

**Vanilla Recording**
*Unavailable*

**Additional context**
*N/a*

**Comment by Wohlstand** [comment]
A similar one bug I got when I had to throw a vegetable up and tried to dig the sand when vegetable got touched the player :grin:

**Comment by Wohlstand** [comment]
So, this bug happens with ANY NPC which can be caught from the middle (not from the side). There are vegetables mainly and looks like the Rainbow Shell too.

**Comment by 0lhi** [comment]
The Player can die while this happens:

![Scr_2022-09-15_02-08-31](https://user-images.githubusercontent.com/74732674/190284080-cf36bc8b-e950-4055-b3d9-1bae3ba1f89d.gif)

(Information will be important for later.)

**Comment by Wohlstand** [comment]
This is very old vanilla bug, the same happens with veggies too. I met that bug a while ago in 2013.

**Comment by ds-sloth** [comment]
This should be fixed now in the main and stable branches. The new logic cancels the digging motion in the same way that it is cancelled when digging grass.

![Scr_2024-08-31_13-36-44](https://github.com/user-attachments/assets/82c1d7ce-c0fe-48db-8f26-87fc44aff177)

**Comment by Trickiy** [comment]
I can't trigger this bug on build f7060c0 so I can say this is fix on 3ds at least.

**Comment by ds-sloth** [comment]
Thank you for the test!

@ChristianSilvermoon , how about you?

**Comment by ChristianSilvermoon** [comment]
> Thank you for the test!
> 
> @ChristianSilvermoon , how about you?

Sorry for the very late reply - I can confirm that this issue no longer occurs for me in Main

**Comment by ds-sloth** [comment]
Not to worry, thanks a lot for the confirmation!
