### ISSUE TITLE
(Feature Request) Player's name change in the episode's menu

### ISSUE THREAD

**Issue by P-Star7** [TheXTech/TheXTech#139]
This change makes the "X" in "X Game" textbox when choosing the playable character for an episode read from the episode's .wldx file, where the creator can type the five names to use, similar to the credits option. This means that Mario, Luigi, Peach, Toad, and Link are the default names when the .wld or .wldx file does not provide any data.

**Comment by DerpyBubblez** [comment]
Pretty sure I asked Wohlstand about this, and it would be done through gameinfo.ini (which is already an option. It just needs to be able to be read from an Episode's folder).

**Comment by Wohlstand** [comment]
I guess, I have the ability to change player names at WLDX format, that feature has came with SMBX-38A

**Comment by P-Star7** [comment]
> Pretty sure I asked Wohlstand about this, and it would be done through gameinfo.ini (which is already an option. It just needs to be able to be read from an Episode's folder).

Which options are already in gameinfo.ini? I have not heard about this before.

**Comment by DerpyBubblez** [comment]
Renaming the characters can be done through gameinfo.ini. You can see it in Adventures of Demo.

**Comment by ds-sloth** [comment]
Superseded by #402 and #718
