### ISSUE TITLE
Hub-styled world glitch: Player goes to main hub's last warp number instead of last position

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#196]
**Describe the issue**

When player is died or passed the level, player goes to main hub's last warp number of position instead of last entered position.

**Example Case**

The Boo Adventure 2, WORLD 1-1 then return to MAIN LEVEL

**Recording**

![Scr_2021-10-01_07-28-24](https://user-images.githubusercontent.com/37089530/135543741-67296f63-131a-4800-8d48-bba7a045854d.gif)

**Vanilla Recording**

None

**Comment by Wohlstand** [comment]
It's fully banilla bug:
I ran on WinXP VM, because on Linux this damn crashes with "Invalid Picture" runtime error on attempt to enter the world.
https://user-images.githubusercontent.com/6751442/135545091-5c49a347-e22f-4b90-ac1b-723539ba54c5.mp4

**Comment by Wohlstand** [comment]
The only thing to completely resolve this mess, I should implement the sub-hubs concept where together with the main hub are external sub-hub levels were made.
