### ISSUE TITLE
Attempt to spin-jump (or just) into clown car at specific moment, makes it hurtable at sides

### ISSUE THREAD

**Issue by Wohlstand** [TheXTech/TheXTech#213]
While I worked on the fix of the shoe + conveyor bug, I accidentally found another vanilla bug related to the clown car. Initially I though I broke something, but nope, it's a true vanilla bug.

The reproduction using TheXTech 1.3.5.2:
![Scr_2021-10-18_03-46-56](https://user-images.githubusercontent.com/6751442/137651687-b343f95b-e383-4823-a8ed-2b6291fa3338.gif)

Same case at SMBX2:
![2021-10-18_03_48_20](https://user-images.githubusercontent.com/6751442/137651707-b2adcad2-51cc-41e0-b18e-60d2aca7373b.gif)

And absolutely the same case in SMBX 1.3:

https://user-images.githubusercontent.com/6751442/137651912-616cef03-20da-4a4e-a9cb-a98e7e011afd.mp4

Getting this bug reproduced is tricky, because you need to sit into the clown car before touching it while spinjumping.

Demo level: [Clown car that hurts.lvl.zip](https://github.com/Wohlstand/TheXTech/files/7361203/Clown.car.that.hurts.lvl.zip)

**Comment by 0lhi** [comment]
The Clown Car Hitbox should be changed in General. In SMBX, there is a super big Hitbox which makes it a pain to deal with lava or projectiles. Neither of those cause harm when touching the Clown Car in Mario Maker, only when they touch the Character. That's how it should be for TheXTech, as well.

![Scr_2021-10-18_13-05-33](https://user-images.githubusercontent.com/74732674/137719716-af7e87ec-1a65-494a-b2bf-9add8261bed3.gif)

**Comment by ds-sloth** [comment]
This should now be fixed in the main and stable branches. Please let me know if it looks correct to you also.

**Comment by Wohlstand** [comment]
Whoops, I forgot to verify that, it was done a while ago..

**Comment by Wohlstand** [comment]
Okay, verified, works everything just fine!
