### ISSUE TITLE
SMBX Classic Hud (SMBX 1.0 - 1.0.2) for TheXTech

### ISSUE THREAD

**Issue by vitzie629** [TheXTech/TheXTech#218]
![SMBX_Hud_Differences](https://user-images.githubusercontent.com/90484844/138515604-32690ce7-fc51-40d8-9172-3f5d7ec8a0b6.png)
I have a suggestion for TheXTech, and that is reviving the classic hud as pictured above (1-player and 2-player variants) which was used in SMBX 1.0 - 1.0.2. The classic hud should be configured by the config.ini file for SMBX 1.0 levels and episodes in TheXTech!

**Comment by P-Star7** [comment]
This should have a config to auto-load it in 1.0 episodes.

**Comment by vitzie629** [comment]
> episodes.

Excellent thinking regarding the hub having a config to auto-load for 1.0 levels and episodes.

**Comment by LoveBodhi** [comment]
https://www.smwcentral.net/?p=section&a=details&id=21562 (Ladida's Minimalist HUD, which is remade by Hatsune Blake), should be added on?

Therefore, we have 4 different style of HUD (Status Bar).

**Comment by vitzie629** [comment]
> https://www.smwcentral.net/?p=section&a=details&id=21562 (Ladida's Minimalist HUD, which is remade by Hatsune Blake in SMBX2B4 https://www.supermariobrosx.org/forums/viewtopic.php?f=101&p=389175#p389175), should be added on?
> 
> Therefore, we have 4 different style of HUD (Status Bar).

Excellent idea, and I would like it!

**Comment by Wohlstand** [comment]
Btw, as an idea, what about making the sort of a `hud.ini` where users are able to customize the overlay for their needs? (In additional to future scripts) this file could be placed assets root, at episode, or at level custom directory and something also.

**Comment by LoveBodhi** [comment]
This should be fine

**Comment by ChristianSilvermoon** [comment]
Hmm, something like [This Minimal Status Bar thingy for SMW](https://www.smwcentral.net/?p=section&a=details&id=21562) could also be really good for smol resolutions maybe.

**Comment by LoveBodhi** [comment]
Anyways, this should be done by XTLua script system...

**Comment by LoveBodhi** [comment]
... Same sense for NsPr Status Bar.
