### ISSUE TITLE
Disable Spin-Jump by remapping 'Alt Jump' to 'Jump' on certain conditions

### ISSUE THREAD

**Issue by 0lhi** [TheXTech/TheXTech#269]
While playing through a [LunaDLL Episode](https://talkhaus.raocow.com/viewtopic.php?f=47&t=15054) that disables Spin-Jumps, I noticed that The Alt Jump button doesn't work at all:

![Scr_2022-01-31_20-21-13](https://user-images.githubusercontent.com/74732674/151858907-7cdba1d7-39a0-440a-aa86-1f155ba7dd70.gif)

This can lead to unexpected deaths.

I therefore suggest to set the ```Alt Jump``` buttons as tertiary and quaternary inputs for ```Jump``` if one of those 3 conditions is met:

1. The Autocode is disabling Spin-Jumps.
2. compat.ini has a ```disable-spinjump = true``` entry.
3. SMBX Version is lower than 20 and Pre-1.3 Adjustments are enabled (see #185).

In either of these cases, the Controller Display should give the Alt Jump input a green color:

![ALTJUMPtoJUMP](https://user-images.githubusercontent.com/74732674/151860514-9a2b45e6-f638-4dc9-9dae-aedfedcda1b2.png)

If possible, it would be great to have the remap only occur during Gameplay (including CaptainN), but not in the Pause Menus (including the Cheat Keyboard and Drop/Add).

**Comment by ds-sloth** [comment]
I think this is interesting but I don't think I have time to develop it right now. However, I'm happy to talk about the proposed feature and see if we can agree on an implementation.

First, I want to understand your intended policy. Are you saying that Alt Jump should only be disabled when `PauseGame == PauseCode::None`, and if it is disabled, any Alt Jumps should be replaced by Jumps? Are there any compat modes where this would be problematic?

If we want to fix the fact that most current code disabling Alt Jumps completely cancels the Alt Jump, I propose a few steps:
- Whenever *we* disable Alt Jumps, replace that with a conversion into a normal Jump. Make sure we don't do this if the game is paused for any reason.
- Whenever autocode / lua (eventually) cancels an Alt Jump, use a heuristic to convert it into a regular Jump. The goal of the heuristic is to make sure that the script would not have canceled a regular Jump. The heuristic says that if `Player[A].Controls.AltJump` switches from `true` to `false`, and `Player[A].Controls.Jump` is neither read nor written in the same script frame, then `Player[A].Controls.Jump` should switch from `false` to `true`.

How do these steps seem to the two of you?

Recoloring the Alt Jump on the controller display would be tricky and I'm not sure it is needed. But if you think it is important, we can set a per-player flag that the Alt Jump should be recolored. (I always try to avoid introducing new flags like this just to avoid RAM bloat.)

**Comment by Wohlstand** [comment]
The fact; at older SMBX builds the alt-jump button just didn't existed at all, so, to replicate old SMBX at some cases, really need to disable altrun and altjump here, or yes, for people's convenience, forward into normal run/jump.

**Comment by 0lhi** [comment]
> First, I want to understand your intended policy. Are you saying that Alt Jump should only be disabled when ```PauseGame == PauseCode::None```, and if it is disabled, any Alt Jumps should be replaced by Jumps?

Yes! It's important to keep the Alt Jump in Pause Screens in case we want to assign it to something.

> Are there any compat modes where this would be problematic?

I couldn't think of any.

> * Whenever _we_ disable Alt Jumps, replace that with a conversion into a normal Jump. Make sure we don't do this if the game is paused for any reason.
> 
> * Whenever autocode / lua (eventually) cancels an Alt Jump, use a heuristic to convert it into a regular Jump. The goal of the heuristic is to make sure that the script would not have canceled a regular Jump. The heuristic says that if `Player[A].Controls.AltJump` switches from `true` to `false`, and `Player[A].Controls.Jump` is neither read nor written in the same script frame, then `Player[A].Controls.Jump` should switch from `false` to `true`.

Seems good? If the end result for the user is the same in both cases, it should be good ^^

> Recoloring the Alt Jump on the controller display would be tricky and I'm not sure it is needed. But if you think it is important, we can set a per-player flag that the Alt Jump should be recolored. (I always try to avoid introducing new flags like this just to avoid RAM bloat.)

Recoloring would be nice, but it's not important. It is important`that the Alt Jump input will trigger the Alt Jump button though.

**Comment by ds-sloth** [comment]
I added a new compatibility flag `disable-spin-jump`, which causes the `AltJump` key to map to a normal jump, but still allows players to dismount. This flag also prevents Superb Demo Sisters from forcing the player's `CanAltJump` value to `false`, allowing the AltJump key to function as a normal jump in that episode.

![Scr_2024-06-23_22-07-04](https://github.com/TheXTech/TheXTech/assets/72112344/527cf072-984c-4616-8b91-04d5c50ab4ab)

I no longer want to recolor the controller icon, because the `AltJump` key still has different behavior from the normal `Jump` key (ie, allows dismounts).

**Comment by 0lhi** [comment]
Works!
