### ISSUE TITLE
Optional Dynamic Message System

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#335]
![dynamessagetest](https://user-images.githubusercontent.com/37089530/170821244-15c0f51e-9a9a-4392-90cc-01f6b7afc236.gif)
I wish there's dynamic message system like above (Hello Mario Engine's message system)...

**Comment by ChristianSilvermoon** [comment]
> ![dynamessagetest](https://user-images.githubusercontent.com/37089530/170821244-15c0f51e-9a9a-4392-90cc-01f6b7afc236.gif) [ ](https://user-images.githubusercontent.com/37089530/170821244-15c0f51e-9a9a-4392-90cc-01f6b7afc236.gif) ![dynamessagetest](https://user-images.githubusercontent.com/37089530/170821244-15c0f51e-9a9a-4392-90cc-01f6b7afc236.gif) [ ](https://user-images.githubusercontent.com/37089530/170821244-15c0f51e-9a9a-4392-90cc-01f6b7afc236.gif) I wish there's dynamic message system like above (Hello Mario Engine's message system)...

What makes it dynamic?

**Comment by LoveBodhi** [comment]
Per-character appearing.

**Comment by ChristianSilvermoon** [comment]
> Per-character appearing.

Oh, a typing animation!

I'd say if it's added a compat option for `msg-speed` should be added, specifying the delay between characters in milliseconds. A value of 0 should cause it to behave like normal (instant; no animation)

And in Speed Run modes it should default to no animation

**Comment by 0lhi** [comment]
Also users should be able to opt-out of the animation, either with a button press or with an option setting or both.

**Comment by LoveBodhi** [comment]
I found it's a duplicated of #195 !!!

**Comment by ChristianSilvermoon** [comment]
> I found it's a duplicate of #195 !!!

These are similarly named, but they're two different feature requests :P
#335 refers to adding support for a typing animation
#195 refers to adding support for showing a box that doesn't interrupt gameplay for certain NPCs

So this is not really a duplicate of #195 unless we merge the two ideas into one issue
