### ISSUE TITLE
Implement ability for user to change the general music and sound volume

### ISSUE THREAD

**Issue by Wohlstand** [TheXTech/TheXTech#369]
There are controllers that defines the general volume of music and SFX, so, user could mute some of (the music or sound effects), or could increase the gaining factor.

- This controller should be a general volume setting defined by the user, not by scripts
- When scripts were able to manipulate volumes of SFX or music, the volume will be scaled by the general volume factor.

**Comment by LoveBodhi** [comment]
My suggession:

```
music-volume = n
sound-volume = n
```

**Comment by ds-sloth** [comment]
It will be nice to do this after merging the Config Branch

**Comment by ds-sloth** [comment]
This should now be implemented at the Config Branch, let me know if it looks good to you.

**Comment by Wohlstand** [comment]
Also, this was been completed a while ago, and I tested this a while ago too. So, just closing.
