### ISSUE TITLE
[Feature Request] 'Resource Packs' ala like minecraft

### ISSUE THREAD

**Issue by RunninPigeon** [TheXTech/TheXTech#502]
For example, SFX, music, and player skins could be changed by opening the setting menu and opening 'Custom Packs' adding a whole new box of customizability.

**Comment by LoveBodhi** [comment]
This makes me think about a mod, Mario Kart Wii Deluxe.
This also helps me to splitted version of Nostalgic Paradise.

**Comment by GoombarioFan** [comment]
Sounds related to #261.

**Comment by ds-sloth** [comment]
It's a very good idea but mostly a duplicate of #291, which we're internally developing. Thanks for the suggestion!
