### ISSUE TITLE
Bottom-spawned NPCs have incorrect height?

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#577]
I saw a rumor in the codehaus Discord server that NPCs spawned from the bottom of blocks have their height forced to 32px.

GIF credit to Ness-Arrrgsday in that server:

<img width="400" height="300" src="https://github.com/Wohlstand/TheXTech/assets/72112344/30987de9-92ea-495e-a4fd-d8880ffcb9f4">

It would be nice to analyze and confirm this, and consider fixing it. It might be an easy fix, and it would be one less surprise for content creators. A lot of creators don't test with Char 5 or with the Pound move.

**Comment by Wohlstand** [comment]
This is fully vanilla bug, I know it for a while. I should try to record on SMBX Experiments.

**Comment by ds-sloth** [comment]
This is a non-critical vanilla bug (it doesn't harm the player, but it clearly puts the affected NPCs in an invalid state). I think it would be useful to implement it after the Config Update and enable in Modern (but not Classic) mode.

**Comment by ds-sloth** [comment]
This should be fixed now, and I also fixed a graphical bug where an NPC emerging upwards sometimes uses the wrong frame. I'll send these fixes to 1.3.6.5 as well.

@Wohlstand, can you please test this to confirm it is working before we close it?

**Comment by Wohlstand** [comment]
I'll try to test this tomorrow

**Comment by ds-sloth** [comment]
Was already included in 1.3.6.5 release.
