### ISSUE TITLE
Customizable "Font 5"

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#603]
![Scr_2023-08-30_13-56-33](https://github.com/Wohlstand/TheXTech/assets/37089530/5b2ffa79-2add-4b7f-be72-026bb698fdfb)

This is Font 4 (Message) + black colour, and the border colour is not customizable. "overrides" (in the `[font-overrides]` section) with 5 is not work, either.

**Comment by LoveBodhi** [comment]
In the latest development (Nightly) build, Font 5 is the "UI Font", while Font 3 is now "Main Menu Font".

**Comment by ds-sloth** [comment]
This will also significantly improve performance on low-end targets. I'll mark it as planned for 1.3.7.

**Comment by LoveBodhi** [comment]
![Scr_2024-04-05_11-29-17](https://github.com/TheXTech/TheXTech/assets/37089530/19ae4867-a568-4a47-b8ae-d62f93440f7f)

**Comment by ds-sloth** [comment]
This should be implemented now, and there is an example in the Adventures of Demo asset pack. Can you please confirm that this works in your asset pack as well?

**Comment by LoveBodhi** [comment]
![Scr_2024-04-05_21-58-07](https://github.com/TheXTech/TheXTech/assets/37089530/f750ae40-7635-4ba5-a587-4fd0e0a0d875)
But not apply to pause manu

**Comment by ds-sloth** [comment]
> Pause Menu

Uses Font 4, not Font 5

> Character Select

Good note, this should be fixed

> TTF

There is an option to control TTF outlines in the main font INI, I guess you noticed this and edited your comment.

**Comment by LoveBodhi** [comment]
> I guess you noticed this and edited your comment.

TTF has no problem, so I removed from the comment.
