### ISSUE TITLE
Implement the sub-hubs system

### ISSUE THREAD

**Issue by Wohlstand** [TheXTech/TheXTech#641]
Sub-hubs - levels are considered as part of main hub, but they were done as separated levels.

There are two known examples I can give:
- "Sarasaland Adventure 2" by Otabo (packed game).
- "The Boo Adventure 2" (Episode for SMBX).

Currently, player must quit the sub-hub to get ability to save the level. Also, if player takes an exit at the third-layer level (a level entered inside sub-hub), player will quit from the main hub at unexpected entrance (see #196, vanilla bug).

## To resolve this, the sub-hubs concept is needed:
- Add a mark to each level "is sub-hub" that will be handled by the engine.
- When player appears at sub-hub, it should be remembered separately from the main hub.
- When player loses their character at sub-hub, player will resume at last entered door ot at start point of sub-hub.
- When player loses their character at level entered from the recent sub-hub, player should enter the recent sub-hub from the last entered door (the same door as being used to enter the level).
- Player must be able to save the game while at sub-hub.
- When resuming game from the main menu, player must appear at the sub-hub instead of the main hub.

**Comment by LoveBodhi** [comment]
Sorts like Open Areas in SMB Wonder

**Comment by SkullGamer205** [comment]
Another Example: Super Mario Star Expedition.
HUB: main level
Sub-hubs: World hubs
