### ISSUE TITLE
[Vanilla Bug] Hitting a bomb tower only will explode the hit Bomb and below

### ISSUE THREAD

**Issue by M0REKZ** [TheXTech/TheXTech#672]
**Describe the issue**

Try to make a tower of SMB2 bombs and throw an object into it, if you hit it in the middle, only the bombs from the middle and below will explode.

Note that, as shown in the gif, the entire SMB2 Bob-ombs actually explodes if they touch the wall on the right.

**Example Case**

Example level with Mouser bombs and SMB2 Bob-ombs here: ~~[BombTower.lvlx.zip](https://github.com/Wohlstand/TheXTech/files/13721703/BombTower.lvlx.zip)~~
Vanilla format: [BombTower.lvl.zip](https://github.com/Wohlstand/TheXTech/files/13722161/BombTower.lvl.zip)

Vanilla bug found in *level 5.lvl* from [Difficulted mario](https://smbxarchive.wohlsoft.ru/SMBX%201.3/Difficulted%20mario%20english%201.4%20by%20%2BKZ%20SBGamer.zip)    

**Recording**

![bomb-bug](https://github.com/Wohlstand/TheXTech/assets/60852359/246d850f-4fab-4989-b158-d2c0fcec7a02)

**Vanilla Recording**

https://github.com/Wohlstand/TheXTech/assets/60852359/02d2c883-7767-4615-8522-86fa416e3626

(I had to lower video quality to submit it to Github)

**Additional context**

TheXTech 1.3.7-dev (branch main, commit 88c0447)
SMBX 1.3.0.1
Virtual Machine: Windows 11 ARM64

**Comment by Wohlstand** [comment]
A pro tip: you can produce vanilla recordings as GIFs using my experiments branch: https://github.com/Wohlstand/smbx-experiments/releases/tag/2023-10-31-1, it has built-in GIF recorder. You can download the small package only and mix it with your existing copy of SMBX, and run the "smbx-r.exe" to use the advanced thing.

**Comment by M0REKZ** [comment]
> A pro tip: you can produce vanilla recordings as GIFs using my experiments branch: https://github.com/Wohlstand/smbx-experiments/releases/tag/2023-10-31-1, it has built-in GIF recorder. You can download the small package only and mix it with your existing copy of SMBX, and run the "smbx-r.exe" to use the advanced thing.

Good idea, maybe ill try it later.
Also realized that i submit the level in modern format, let me fix that 🥶

**Comment by ds-sloth** [comment]
Very nice find! We won't fix this in TheXTech (see https://github.com/Wohlstand/TheXTech/wiki/Types-of-bugs), but we appreciate you bringing it to our attention.
