### ISSUE TITLE
[Vanilla Bug] Vertical collision fails when placing multiple NPCs above a jumping one

### ISSUE THREAD

**Issue by M0REKZ** [TheXTech/TheXTech#673]
**Describe the issue**

_Only tested with Ninji_

Trying to place multiple enemies above Ninji as a tower will make them fall.

**Example Case**

Example Level linked here: [Towerenemybug.lvl.zip](https://github.com/Wohlstand/TheXTech/files/13721887/Towerenemybug.lvl.zip)

Vanilla bug found in *level 6.lvl* from [Difficulted mario](https://smbxarchive.wohlsoft.ru/SMBX%201.3/Difficulted%20mario%20english%201.4%20by%20%2BKZ%20SBGamer.zip)    

**Recording**

![jumpingbug](https://github.com/Wohlstand/TheXTech/assets/60852359/689cc779-7985-4b9f-a156-ade5ddadbb8c)

**Vanilla Recording**

https://github.com/Wohlstand/TheXTech/assets/60852359/6da7b0f7-7ebc-41e9-86be-0fbd64b74cbf

**Additional context**

TheXTech 1.3.7-dev (branch main, commit https://github.com/Wohlstand/TheXTech/commit/88c04474d17791d09044c430dd317f888953641b)
SMBX 1.3.0.1
Virtual Machine: Windows 11 ARM64

**Comment by ds-sloth** [comment]
Very nice find! We won't fix this in TheXTech (see https://github.com/Wohlstand/TheXTech/wiki/Types-of-bugs), but we appreciate you bringing it to our attention.
