### ISSUE TITLE
Modern item drop

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#722]
The SMBX 1.3 item drop feature is limited to spawning from the item box. This is painful in resolutions much bigger than 800x600.

It could be nice to try making the item drop from directly above the player (but how can we animate that smoothly?). I'll experiment with this some before the 1.3.7 release.

**Comment by SkullGamer205** [comment]
Interesting feature)))

**Comment by Alucard648** [comment]
Be careful with this feature. Some levels are designed to filter away item box contents via locking Mario in a small space then auto-drop reserve item, when it`s unreachable.

**Comment by Wohlstand** [comment]
An example: the boss fight at the "Dream gardens" level of "2k15 Summer Takeover".

**Comment by ds-sloth** [comment]
Thanks to Alucard and Wohlstand for the warning. Here's a possible strategy:
* In modern mode, always place the item directly above the player, except during cutscenes (then, use the item box)
* In classic mode, always use the item box

This would very slightly alter the strategy of the item box during modern mode, but it shouldn't disrupt cutscenes, and would greatly simplify the player experience in multires and multiplayer.

How does that sound to everyone?

I'll start with Krissy's suggestion for the animation, but we can discuss that further after I have a mockup.

**Comment by LoveBodhi** [comment]
So how about the future "Wonder" style item balloon mechanic (with Lua)?

**Comment by ds-sloth** [comment]
That might be supported, or might not. I'm not certain yet. Unlike in X2, it's not intended for Lua to fully alter TheXTech's gameplay logic. (Our first Lua capabilities will be creating new NPCs and player abilities.)

**Comment by LoveBodhi** [comment]
> That might be supported, or might not. I'm not certain yet. Unlike in X2, it's not intended for Lua to fully alter TheXTech's gameplay logic. (Our first Lua capabilities will be creating new NPCs and player abilities.)

So this is conjectural, it's too early to speak about Lua. I'm sorry...

**Comment by ds-sloth** [comment]
That's a good example. I think this is a great reason for the classic mode / modern mode split on this feature.

Do other people agree that it's acceptable if the ability to hang in the air using the item box is lost in modern mode?

**Comment by ChristianSilvermoon** [comment]
> That's a good example. I think this is a great reason for the classic mode / modern mode split on this feature.
> 
> Do other people agree that it's acceptable if the ability to hang in the air using the item box is lost in modern mode?

I don't think I've ever once done this for any practical purpose, so I'm okay with it being lost in Modern Mode ^^

**Comment by ds-sloth** [comment]
![Scr_2024-04-19_09-05-39](https://github.com/TheXTech/TheXTech/assets/72112344/5cf74576-ffdb-4b13-a7c9-0cfbfe7751fd)

This feature is now enabled by default in the Config Branch for testing. Please let us know if you like this implementation on the WohlSoft Forums here: https://wohlsoft.ru/forum/viewtopic.php?f=5&t=4827

**Comment by ds-sloth** [comment]
This feature is now enabled in Modern Mode in current development builds. Any feedback or suggestions would be very welcome.

**Comment by LoveBodhi** [comment]
![Scr_2024-06-24_05-40-04](https://github.com/TheXTech/TheXTech/assets/37089530/af0db1d8-d8af-45e2-99df-d23422bfe7d4)
Test works...

**Comment by M0REKZ** [comment]
So i tested it, and it allows the player to reach the power-up where normally would be unreachable.
However looks like this "cheat" was expected.

![scrn](https://github.com/TheXTech/TheXTech/assets/60852359/efdf8906-9db7-4fb3-9123-afc08d22bca7)

**Comment by ds-sloth** [comment]
0lhi and I have made some additional plans about when to enable / disable this feature:
* enable in shared screen multiplayer
* enable when small screen camera lookahead is enabled
* disable in other single player and multiplayer modes (use #849 instead when the level makes an item inaccessible)

**Comment by 0lhi** [comment]
Tested, works as intended 👍

**Comment by SkullGamer205** [comment]
> 0lhi and I have made some additional plans about when to enable / disable this feature:
> 
>     * enable in shared screen multiplayer
> 
>     * enable when small screen camera lookahead is enabled
> 
>     * disable in other single player and multiplayer modes (use [Hotkey for forcing default cam view #849](https://github.com/TheXTech/TheXTech/issues/849) instead when the level makes an item inaccessible)

What about a toogle this feature manually? (#858)
This feature can be a part of gameplay in new episodes?

**Comment by ds-sloth** [comment]
I'm closing this issue now but #858 is still open and may be developed in a later version of the engine.
