### ISSUE TITLE
Fish die when landing on land

### ISSUE THREAD

**Issue by Shadowblitz16** [TheXTech/TheXTech#735]
**Describe the issue**
Fish die when landing on land even if the land is in water or above water.

**Example Case**
[Fish Bug.lvlx.zip](https://github.com/TheXTech/TheXTech/files/14454343/Fish.Bug.lvlx.zip)

**Recording**

I tried idk how to upload it once I am done recording

**Additional context**

The Dungeon blocks doesn't seem to kill the fish when out of water but I tested this like a week ago and smb3 grass tiles do.

**Comment by ds-sloth** [comment]
Thank you for noting this! This is not in fact a bug, but instead the intended behavior of the fish in SMBX. There are actually many pieces of code designed to make sure that it happens.

**Comment by Shadowblitz16** [comment]
@ds-sloth wouldn't it be better to have the fish swim out of the block into the closest empty body of water?
This breaks platforming water levels.

**Comment by ds-sloth** [comment]
I am glad you brought this to our attention. It's extremely useful for us to have an index of the unexpected behaviors in SMBX, but this really isn't something TheXTech would try to change.

If you want to help the project further, I'd appreciate it if you can check whether your suggestions #702 and #705 are implemented as you requested.

**Comment by Shadowblitz16** [comment]
@ds-sloth I actually reread this and I feel I was not entirely clear in what the issue was. 

The issue is that the fish would jump out of the water and land on the land and die even though water was directly below that land.

What I was suggesting was making it so land had no effect on fish so the fish just passed through back into the water.

If this was the case the fish would fall off the screen if there was no water below the land.

**Comment by ds-sloth** [comment]
I understand this, but that just isn't how SMBX handles jumping fish. I'm sorry.

If you want fish to act this way, maybe talk to Wohlstand and convince him to implement them differently in Moondust?
