### ISSUE TITLE
SMBX2 editor aka Moondust editor deleted my world.

### ISSUE THREAD

**Issue by Shadowblitz16** [TheXTech/TheXTech#737]
**Describe the issue**

I made an issue about this with the x tech in game editor but I just experienced it with worlds in the smbx2 editor with the x tech config pack

**Example Case**

![image](https://github.com/TheXTech/TheXTech/assets/2453707/207bb62e-455c-4aa6-8e40-4e2d60abc4a4)

I had an entire smb3 world 1 map with extended borders due to smbx not supporting map borders
But now the map is suddenly gone.

**Additional context**
I was editing the tileset when it happened

**Comment by Wohlstand** [comment]
I totally can't understand, why Editor should detele anything? And also, SMBX2's editor is totally NOT mine, I don't maintain it. Actually, if you want to report the bug of MAINSTREAM Moondust Devkit, you should report that issue at [THIS](https://github.com/WohlSoft/Moondust-Project/issues) repository.

**Comment by Wohlstand** [comment]
Anyway, Editor itself does NOT delets any files. But, if you creating "new" and saving it over your old one, that's just your own mistake.

**Comment by Wohlstand** [comment]
P.S. It's also possible, that you just missing in the infinite space and you can easily come back to the world map by using the "Reset position" toolbar button (it should appear somewhere at left-top side).

I closing this issue as it:
1) has NOTHING to TheXTech, it's issue to Moondust Editor.
2) SMBX2 Editor is NOT a Moondust Editor (the part of the mainstream Moondust Project maintained by me). And also, they somewhere are incomplatible, and first thing is the lack of extra settings on the world map (sub-hubs list). Second case is format of tilesets files.

**Comment by Wohlstand** [comment]
So, please report problems of Moondust Editor here: https://github.com/WohlSoft/Moondust-Project/issues, not here.
