### ISSUE TITLE
Vanilla bug: blocks become non-solid after coin switch

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#739]
@Wohlstand found a very interesting bug two days ago where some blocks could no longer be destroyed by shells after using a coin switch.

After we verified this bug and did some debugging, I found that this bug is caused by the coin switch code failing to reset certain properties of the blocks that it creates (in particular, `IsReally`, `IsNPC`, and `noProjClipping`). And, Wohlstand confirmed that this bug is fully VANILLA!

<img src="https://github.com/TheXTech/TheXTech/assets/72112344/d8c71d12-5e95-4c13-8a8a-1a2f91918c26" width="400" height="300">

This minimal test case is attached here: [CoinSwitchBlockBug.lvl.zip](https://github.com/TheXTech/TheXTech/files/14566380/CoinSwitchBlockBug.lvl.zip)

This bug is of moderate severity, because the affected blocks are still solid to players. Thus, levels may become impossible to beat. However, the bug is reasonably predictable in SMBX64, so this is not likely to make well-tested SMBX 1.3 content unbeatable. We will be enabling this bugfix in Modern Mode in TheXTech 1.3.6.5 and future versions.

**Comment by Wohlstand** [comment]
Tested, everything works just fine now!
