### ISSUE TITLE
Failure to reproduce some single-frame clips

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#741]
While talking with Jedat today, we discovered an extreme rightwards clip (by stacking three layers of blocks and doing a "normal" rightwards clip when the blocks are unsorted), and they mentioned some very interesting single-frame downwards clips (hitting an enemy or player that is overlapping an invisible block, and reverting from character 5's flight form in a 1-block tall space).

[Single-Frame Clips.lvl.zip](https://github.com/TheXTech/TheXTech/files/14625691/Single-Frame.Clips.lvl.zip)

TheXTech 1.3.5:
<img src="https://github.com/TheXTech/TheXTech/assets/72112344/bbe831f3-8930-4af7-91ac-124b4306ce79" width="400" height="300">

TheXTech 1.3.7-dev:
<img src="https://github.com/TheXTech/TheXTech/assets/72112344/d5fd5938-1b73-4c1f-abfa-dce4ab325d1c" width="400" height="300">

All of these clips have failed to reproduce in TheXTech since v1.3.6 due to my block quadtree / lookup table optimizations. The reason is that my lookup queries do not assume that the queried location might move substantially during the loop over results. This can affect NPCs as well (though in fewer circumstances).

Before 1.3.7, I'm going to write a new wrapper class over a tree sentinel, such that something like the following will be valid code (and perform accurately when `BlocksSorted` is either `true` or `false`):

```cpp
UpdatableSpatialQuery<BlockRef_t> query = treeFLBlockQueryUpdatable(p.Location, SORTMODE_COMPAT);

for(BlockRef_t block : query)
{
    if(...)
    {
        p.Location.Y = ...;
        query.update(p.Location);
    }
}
```

**Comment by Wohlstand** [comment]
The player filter clip bug workflow is also affected by this:
1) [Demo level](https://github.com/TheXTech/TheXTech/files/14625742/Deep-going-down.zip)

2) How it goes:
![Scr_2024-03-17_04-02-00_(1)](https://github.com/TheXTech/TheXTech/assets/6751442/f2c3a3f0-1592-4bca-9741-0ae381f2d45f)

3) How it SHOULD be (Recorded via SMBX-R):
![Scr_2024-03-17_04-03-39](https://github.com/TheXTech/TheXTech/assets/6751442/229347b4-65ee-4eeb-a822-4322c681b5ea)

**Comment by ds-sloth** [comment]
<img src="https://github.com/TheXTech/TheXTech/assets/72112344/a030be4c-0849-4a63-9f9d-b0853bf85307" width="400" height="300">


This should be fixed now in the `main` and `stable` branches. Wohlstand, can you please check your test levels as well?

**Comment by Wohlstand** [comment]
Tested just now: it works!
<img src="https://github.com/TheXTech/TheXTech/assets/6751442/4bc612ad-a467-460f-824b-ea40865e8ff0" width="400" height="300"/>
