### ISSUE TITLE
[Editor Bug] Anticheat trap can break levels in the editor

### ISSUE THREAD

**Issue by Superbloxen** [TheXTech/TheXTech#748]
### Describe the issue

How to reproduce the bug (ensure the anticheat trap is enabled in the version you are using)

1: Create a new episode, then create a new level

2: Trigger the anticheat trap by using "redigitiscool" in the editor, which should kill the character and set lives to 0

3: Select "Restart Level" and you will be sent to the title screen instead...

4: Start an episode and enter a level, which causes it to start in editor mode

5: Complete or exit the level, then save and exit

The level is now inaccessible from its original location and appears in the new one that was just created, which will break any appearance of said level in the original episode.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.6.3

### Platform

Web-browser (Emscripten)

### Processor architecture

Not specified / I don't know

### Additional context

Discovered on AoD Web Version

**Comment by Wohlstand** [comment]
Okay, I fixed the bug just now:
<https://github.com/TheXTech/TheXTech/commit/a3cd99eeed172d654da496123bce1380a75f6705>

Once the CI build will complete, please try out this debug version (it's not stable, it's devel): <https://builds.wohlsoft.ru/webassembly/debug-deploy/aod-on-web-debug/> and tell me, does the bug happens for you or it's gone? I going to release the 1.3.6.5 soon, and thix fix will be included.

**Comment by Superbloxen** [comment]
The issue is fixed now, but in the process, I found another bug: Using the anticheat trap doesn't quit the episode and instead teleports player to the center of the map...

**Comment by Wohlstand** [comment]
Weird... going to verify that, but it's another bug, but related to the same system...

**Comment by Superbloxen** [comment]
After testing I can confirm the issue is fixed now. OK to close?

**Comment by Wohlstand** [comment]
Yea, as this has been done, then I will close. Thanks for reporting of this!
