### ISSUE TITLE
[Question] About Vertical Wrap-Around in the Ingame Editor

### ISSUE THREAD

**Issue by Superbloxen** [TheXTech/TheXTech#752]
While reading through Issue #379, I noticed that vertical screen-wrapping was checked as a feature that was already in TheXTech. I found that it was possible to enable this functionality by editing a .lvlx file, but there doesn't seem to be a toggle for this 
in the ingame editor itself. Will this be added in a future update?

**Comment by ds-sloth** [comment]
This is one of the TheXTech-exclusive features that isn't currently available in the editor interface.

The section settings page of the editor is current full. I'll add this at the same time that I make sections resizable without using the four separate cursor modes.

**Comment by ds-sloth** [comment]
This should now be implemented. Please confirm that you can find it. You'll want to do this in a modern world (which should be the default for user-created worlds).

![Scr_2024-05-03_18-27-11](https://github.com/TheXTech/TheXTech/assets/72112344/b0748e83-af92-4bd4-bfaf-2c6ec99f0f1d)

**Comment by Superbloxen** [comment]
> This should now be implemented. Please confirm that you can find it. 

After testing on the web build, I can confirm the option is there and works as intended.

**Comment by ds-sloth** [comment]
Great, thanks for the test!
