### ISSUE TITLE
[Android Bug] Closing and Reopening TheXTech Causes Black Screen

### ISSUE THREAD

**Issue by Superbloxen** [TheXTech/TheXTech#758]
### Describe the issue

By going to a different app for any reason (recent tab or locking and unlocking phone) and returning to TheXTech, the game will open with a black screen and also make the onscreen keyboard appear.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.6.5

### Platform

Android

### Processor architecture

Not specified / I don't know

**Comment by ds-sloth** [comment]
Thanks for the report!

Wohlstand, OpenGL context loss?

If so, we should be able to handle this now (even in the middle of gameplay) but it may be hard to avoid free-ing all the OpenGL resources.

**Comment by Wohlstand** [comment]
If speak about OpenGL, this might happen on some devices when no enough memory, all textures gets being unloaded and it's need to load them back

**Comment by Wohlstand** [comment]
If use OpenGL ES directly, then the thing might unload all the textures while in the background, and it's need to load them back again.

**Comment by ds-sloth** [comment]
If it's a typical context loss, we don't only need to load the textures back, we need to restart the entire renderer (technically we shouldn't call any OpenGL cleanup functions, but depending on implementation, it may be safe to simply call `frmMain.restartRenderer()`).

**Comment by ds-sloth** [comment]
I'm experimenting with a fix for this before the v1.3.7 release.

**Comment by ds-sloth** [comment]
I've tested this fix as working on my own device. This issue should be fixed in the most recent dev build and in the v1.3.7-beta release.

**Comment by Superbloxen** [comment]
Works on my device too, as of 1.3.7-beta.

**Comment by Wohlstand** [comment]
Thanks! Closing now.
