### ISSUE TITLE
"Mono" is not usable for WASAPI (Windows)

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#767]
I'm using Windows 10. Mono is not work for WASAPI (Least channel is 2). Downmix to mono DSP FX is required for workaround...

**Comment by Wohlstand** [comment]
This is a problem of Windows, not of the game. If you want to make WASAPI play mono, you should tweak settings of Audio in your Windows setup, and then WASAPI will report it receives the MONO stream.

**Comment by ds-sloth** [comment]
I think that the "mono" setting should get marked with an "(X)" when you try to set it under WSAPI. Is that correct?

**Comment by LoveBodhi** [comment]
> I think that the "mono" setting should get marked with an "(X)" when you try to set it under WSAPI. Is that correct?

Right!

**Comment by ds-sloth** [comment]
Excellent. Thank you for confirming! Then the engine is working as intended, and as Wohlstand noted this is a problem of the Windows API.
