### ISSUE TITLE
Split Screen Issue On Wii U

### ISSUE THREAD

**Issue by juliobutinblender** [TheXTech/TheXTech#773]
### Describe the issue

Whenever i try playing on multiplayer in the wii u version by some reason the split screen bugs.
In the case of tiramisu one of the screens won't show anything while on aroma it does show the map but all bugged and without any character, enemy or floor. The other screen stays totally frozen in the last frame it was before one of the characters went offscreen for it to split and it stays that way until both are again on the same screen. The behavior does change depending on if the gamepad user is the one to go off screen or the other controller one does. But one of the screens freezes
(In this case i only tried playing with two characters so i'm unsure whenever this also happens with more than 2)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.6.5

### Platform

Wii U

### Processor architecture

Not specified / I don't know

### Recording

![2024-07-11_19 32 16 334_TV](https://github.com/user-attachments/assets/5d5967a9-ff9b-4703-bb72-233863fcb706)
![2024-07-11_19 32 24 909_TV](https://github.com/user-attachments/assets/7c7acfd4-24fd-4238-835f-15c90efc8a77)
![2024-07-11_19 32 47 632_TV](https://github.com/user-attachments/assets/76cf6146-b6f5-4bdd-9766-0d8e0e2cd727)
![2024-07-11_19 33 16 360_TV](https://github.com/user-attachments/assets/fea871ab-6ab3-4067-bd17-7b93edb38aaf)

**Comment by ds-sloth** [comment]
Thanks a lot for the report! We're aware of some similar issues in the version of SDL used in our v1.3.6.5 release.

@Wohlstand, now that we've fixed this issue in the SDL2 side, maybe we should confirm that the fix works in fresh v1.3.6.6 dev builds. We may want to release 1.3.6.6 soon.

**Comment by Wohlstand** [comment]
I'll try to check some today, now I'm a bit busy.

**Comment by Wohlstand** [comment]
I cherry-picked recent tweaks, and the stable branch built with the newer SDL2 works just fine on my hardware:

![20240713_021511.jpg](https://github.com/user-attachments/assets/7749ad30-7254-4e23-96fe-19c62c3b8d0d)

![20240713_021615.jpg](https://github.com/user-attachments/assets/3e6cbbd9-79be-4826-83cb-206f067820da)

![20240713_021735.jpg](https://github.com/user-attachments/assets/87434eda-03ec-41e3-a8db-ff73b6040bb2)

![20240713_021751.jpg](https://github.com/user-attachments/assets/85ca00cd-60bb-4163-a2d7-252f913b5ae6)

**Comment by Wohlstand** [comment]
@juliobutinblender , can you download the `stable-1.3.6.x` CI build and test the result on your end to confirm the problem is resolved?

**Comment by juliobutinblender** [comment]
Alright I'll test it asap

**Comment by juliobutinblender** [comment]
I'm having problems with my computer rn so I'm not exactly sure if I'll be able to compile it and be able to test it, I may need some time or I'm not sure if I can do anything else. It's just an bsod party for an while now

**Comment by Wohlstand** [comment]
@juliobutinblender, ping? Did you tested the thing? Because of no response for so long time, I'll close this.

**Comment by Wohlstand** [comment]
Feel free to re-open if issue is still on your end with the latest stable (or current in-development version).
