### ISSUE TITLE
LunaDLL.txt broken on 3ds

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#776]
As I have played around with the editor on my 3ds I realized. The classic smb timer and game over screens are not toggle able options by default. I wanted to make a Speedrun level but can't because the are no stakes.

**Comment by Superbloxen** [comment]
LunaDLL has a built in timer that you can setup to kill the player after a certain time, I'm not familiar with TheXTech on 3DS but on Android and Desktop you can create a lunadll.txt file with your timer code in it.

**Comment by Wohlstand** [comment]
> on Android and Desktop you can create a lunadll.txt file with your timer code in it.

The thing is pretty same with no matter what platform where TheXTech runs. This thing works on Wii, on Wii U as well as on 3DS. The LunaScript system is pretty portable thing unlike the original LunaDLL.

**Comment by Trickiy** [comment]
My coding know how is next to non-existent, so how would I setup the timer code?

**Comment by Superbloxen** [comment]
You'd set up the code like this:

// Activate #1000 after 600 frames
Timer,0,1000,1,0,600,0

// Time's up
#1000
Kill,0,0,0,0,1,0

#END

You can edit the frame count for the timer to increase or decrease how much time will be left in the countdown. Additionally, you can check [this page on the Moondust Wiki](https://wohlsoft.ru/pgewiki/Category:LunaDLL) for more information on Autocode scripts in general.

**Comment by Trickiy** [comment]
@Wohlstand The Timer code for some reeason is broken on my new 2ds xl.

**Comment by Wohlstand** [comment]
Lemme check some...

**Comment by Superbloxen** [comment]
That's my fault, the top of the code I sourced from the wiki was cutoff so it displays an error message..

Here's the working code:

#0

// Activate #1000 after 600 frames
Timer,0,1000,1,0,600,0

// Time's up
#1000
Kill,0,0,0,0,1,0

#END

**Comment by Trickiy** [comment]
> That's my fault

It's not your fault Superbloxen because I was already put #0 when I tried to run the code.

**Comment by Trickiy** [comment]
Sorry for causing a false alarm, I just figured out that if I want to make the code work. I just needed to put the LunaDLL.txt file into a folder named the same as the level.
