### ISSUE TITLE
Modifiable hit points & toggle unstompable enemies

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#777]
Adding the ability to change how many hits it takes to kill a enemy and have any enemies be unstompable to the editor. Could make for some interesting link levels. I realize I am asking for mini bosses to be added.

**Comment by Wohlstand** [comment]
With the LunaScript (LunaDLL dialect) you can alternate the health level of any boss enemy. You need to set an initial value to the `NPC_t::Damage` field ([see the map](https://github.com/TheXTech/TheXTech/wiki/LunaScript-Memory-Map#npc-memory)). Actually, in the tutorial is an example: https://github.com/TheXTech/TheXTech/wiki/LunaScript-Autocode-scripts#modify-boss-life

**Comment by Superbloxen** [comment]
This is (partially) in TheXTech, you can make an npc-x.txt (replace X with the NPC ID of your enemy) and there you can configure it with the flag jumphurt=1 to make the enemy deal damage when you try to stomp on them. For now, only boss NPCs can be configured to have more HP. 

Certain NPCs have hardcoded behavior and don't change when you edit their properties with a npc-x.txt file, but this could change in the future if these ideas (#384 & #379) get added to the game, though the main developers of the project are busy with implementing other content and could work on these at a later time.

**Comment by Trickiy** [comment]
Thanks this info is very helpfull.
