### ISSUE TITLE
Pushable layer LnaDLL.txt unknown command error

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#778]
### Describe the issue

When I try to run [this](https://github.com/TheXTech/TheXTech/wiki/LunaScript-Autocode-scripts#pushable-layer) example code the following error occurs.
![image](https://github.com/user-attachments/assets/6cd6e9a0-41ac-42ad-b42f-a4cb3dc10044)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.6.5

### Platform

3DS

### Processor architecture

None

**Comment by ds-sloth** [comment]
I believe that the command is AccelerateLayerX (or AccelerateLayerY). Does that help?

**Comment by Trickiy** [comment]
Ok adding the x to accelerate has stopped the error. But now I can't figure out why nothing happens when I try walking into the wood block.

**Comment by Trickiy** [comment]
It's Working now Thanks I simply needed to add the x that I missed and make a fourth layer. Now I know that the layers go default= layer 0, Destroyed Blockes =layer 1  and spawned npc's = layer 2. Any layer I add after layer 2 increments by 1 more, this should be added to the wiki for dumbys like myself unless I glossed over it.
