### ISSUE TITLE
Missing Set Bounds arrows

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#780]
### Describe the issue

In the latest dev build the bounds arrows are missing but in Lopez tutorials custom cia build they are visible. (Since I mentioned the cia build could there be a official build.)
dev build: 
![image](https://github.com/user-attachments/assets/2349ef48-8d58-472a-be85-c6c74b111798)
cia build: 
![image](https://github.com/user-attachments/assets/5aa32620-bc71-4c44-b88d-70ba3ffe7e60)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

bb07af2

### Platform

3DS

### Processor architecture

None

**Comment by ds-sloth** [comment]
The section bounds are now updated by double-tapping and dragging with the stylus. Sorry for the confusion.
<img src="https://github.com/user-attachments/assets/4aa46f19-56b6-496d-8ee8-2a95d0fc6b44" width="640" height="360">

**Comment by Trickiy** [comment]
For some reason when I double tap and drag nothing happens.
