### ISSUE TITLE
ability to chose which assets are used before loading

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#785]
I tried running the latest devel 3dsx with the assets of Adventure of Demo it will not load past sound bubble.ogg locking up the 3ds. Here's the log of the attempt:
00:00.023 [Info]: Application started>
00:00.042 [Info]: TheXTech 1.3.7-dev (branch main, commit b786ff5)
00:00.054 [Info]: Initialized XRender with 26387456 bytes free
00:00.155 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.266 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.327 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.443 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.509 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.578 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.706 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.786 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.875 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:00.969 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.099 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.201 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.272 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.392 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.481 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.542 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.655 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.758 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.866 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:01.977 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.079 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.142 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.250 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.333 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.395 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.456 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.569 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.630 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.701 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.828 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.910 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:02.989 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.108 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.179 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.244 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.353 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.420 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.479 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.696 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.811 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.898 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:03.986 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.051 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.167 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.255 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.317 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.430 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.546 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.639 [Warning]: File /3ds/thextech/graphics/ui/MenuGFX1-3ds.t3x doesn't exist, trying to load generic one...
00:04.678 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.781 [Warning]: File /3ds/thextech/graphics/ui/MenuGFX2-3ds.t3x doesn't exist, trying to load generic one...
00:04.820 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:04.977 [Warning]: File /3ds/thextech/graphics/ui/MenuGFX3-3ds.t3x doesn't exist, trying to load generic one...
00:05.016 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.129 [Warning]: File /3ds/thextech/graphics/ui/MenuGFX4-3ds.t3x doesn't exist, trying to load generic one...
00:05.168 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.354 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.524 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.590 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.651 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.715 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.778 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.841 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:05.953 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.018 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.082 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.218 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.279 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.344 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.405 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.472 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.622 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.689 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.750 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.813 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.888 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:06.982 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:07.055 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:07.229 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:07.352 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:07.465 [Warning]: lazyLoadPicture: Couldn't open size file. Giving up.
00:46.101 [Info]: Will load SFX /3ds/thextech/sound/player-shrink.ogg as a multi-music
00:46.211 [Info]: Will load SFX /3ds/thextech/sound/player-grow.ogg as a multi-music
00:46.299 [Info]: Will load SFX /3ds/thextech/sound/mushroom.ogg as a multi-music
00:46.491 [Info]: Will load SFX /3ds/thextech/sound/player-died.ogg as a multi-music
00:47.122 [Info]: Will load SFX /3ds/thextech/sound/item-dropped.ogg as a multi-music
00:48.121 [Info]: Will load SFX /3ds/thextech/sound/lava.ogg as a multi-music
00:48.310 [Info]: Will load SFX /3ds/thextech/sound/warp.ogg as a multi-music
00:48.669 [Info]: Will load SFX /3ds/thextech/sound/level-win.ogg as a multi-music
00:48.782 [Info]: Will load SFX /3ds/thextech/sound/boss-beat.ogg as a multi-music
00:48.982 [Info]: Will load SFX /3ds/thextech/sound/dungeon-win.ogg as a multi-music
00:49.075 [Info]: Will load SFX /3ds/thextech/sound/bullet-bill.ogg as a multi-music
00:50.320 [Info]: Will load SFX /3ds/thextech/sound/newpath.ogg as a multi-music
00:50.437 [Info]: Will load SFX /3ds/thextech/sound/level-select.ogg as a multi-music
00:50.583 [Info]: Will load SFX /3ds/thextech/sound/do.ogg as a multi-music
00:51.006 [Info]: Will load SFX /3ds/thextech/sound/key.ogg as a multi-music
00:51.017 [Warning]: ERROR: SFX '/3ds/thextech/sound/pswitch.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.029 [Warning]: ERROR: SFX '/3ds/thextech/sound/tail.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.042 [Warning]: ERROR: SFX '/3ds/thextech/sound/racoon.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.051 [Warning]: ERROR: SFX '/3ds/thextech/sound/boot.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.060 [Warning]: ERROR: SFX '/3ds/thextech/sound/smash.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.069 [Warning]: ERROR: SFX '/3ds/thextech/sound/thwomp.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.082 [Warning]: ERROR: SFX '/3ds/thextech/sound/birdo-spit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.092 [Warning]: ERROR: SFX '/3ds/thextech/sound/birdo-hit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.101 [Warning]: ERROR: SFX '/3ds/thextech/sound/smb2-exit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.111 [Warning]: ERROR: SFX '/3ds/thextech/sound/birdo-beat.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.121 [Warning]: ERROR: SFX '/3ds/thextech/sound/npc-fireball.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.134 [Warning]: ERROR: SFX '/3ds/thextech/sound/fireworks.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.144 [Warning]: ERROR: SFX '/3ds/thextech/sound/bowser-killed.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.154 [Warning]: ERROR: SFX '/3ds/thextech/sound/game-beat.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.164 [Warning]: ERROR: SFX '/3ds/thextech/sound/door.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.177 [Warning]: ERROR: SFX '/3ds/thextech/sound/message.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.187 [Warning]: ERROR: SFX '/3ds/thextech/sound/yoshi.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.196 [Warning]: ERROR: SFX '/3ds/thextech/sound/yoshi-hurt.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.208 [Warning]: ERROR: SFX '/3ds/thextech/sound/yoshi-tongue.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.218 [Warning]: ERROR: SFX '/3ds/thextech/sound/yoshi-egg.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.233 [Warning]: ERROR: SFX '/3ds/thextech/sound/got-star.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.242 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-kill.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.252 [Warning]: ERROR: SFX '/3ds/thextech/sound/player-died2.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.262 [Warning]: ERROR: SFX '/3ds/thextech/sound/yoshi-swallow.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.272 [Warning]: ERROR: SFX '/3ds/thextech/sound/ring.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.286 [Warning]: ERROR: SFX '/3ds/thextech/sound/dry-bones.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.295 [Warning]: ERROR: SFX '/3ds/thextech/sound/smw-checkpoint.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.305 [Warning]: ERROR: SFX '/3ds/thextech/sound/dragon-coin.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.315 [Warning]: ERROR: SFX '/3ds/thextech/sound/smw-exit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.329 [Warning]: ERROR: SFX '/3ds/thextech/sound/smw-blaarg.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.339 [Warning]: ERROR: SFX '/3ds/thextech/sound/wart-bubble.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.349 [Warning]: ERROR: SFX '/3ds/thextech/sound/wart-die.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.358 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-block-hit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.368 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-killed.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.383 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-hurt.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.395 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-glass.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.405 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-boss-hit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.415 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-cry.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.428 [Warning]: ERROR: SFX '/3ds/thextech/sound/sm-explosion.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.437 [Warning]: ERROR: SFX '/3ds/thextech/sound/climbing.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.447 [Warning]: ERROR: SFX '/3ds/thextech/sound/swim.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.456 [Warning]: ERROR: SFX '/3ds/thextech/sound/grab2.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.465 [Warning]: ERROR: SFX '/3ds/thextech/sound/smw-saw.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.478 [Warning]: ERROR: SFX '/3ds/thextech/sound/smb2-throw.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.487 [Warning]: ERROR: SFX '/3ds/thextech/sound/smb2-hit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.496 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-stab.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.505 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-hurt.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.518 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-heart.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.528 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-died.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.538 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-rupee.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.548 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-fire.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.558 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-item.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.572 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-key.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.584 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-shield.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.594 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-dash.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.604 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-fairy.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.617 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-grass.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.627 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-hit.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.637 [Warning]: ERROR: SFX '/3ds/thextech/sound/zelda-sword-beam.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.646 [Warning]: ERROR: SFX '/3ds/thextech/sound/bubble.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.657 [Warning]: ERROR: SFX '/3ds/thextech/sound/timeout.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.671 [Warning]: ERROR: SFX '/3ds/thextech/sound/bat-wings.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.680 [Warning]: ERROR: SFX '/3ds/thextech/sound/iceball.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.690 [Warning]: ERROR: SFX '/3ds/thextech/sound/hog_freeze.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.700 [Warning]: ERROR: SFX '/3ds/thextech/sound/ice_break.ogg' loading error: Mix_LoadWAV_RW with NULL src
00:51.710 [Warning]: ERROR: SFX '/3ds/thextech/sound/sprout-vine.ogg' loading error: Mix_LoadWAV_RW with NULL src

**Comment by Wohlstand** [comment]
Did you used the general pacakge rather than 3DS specific? Does other games loads fine? AoD technically is very similar to SMBX in sense of same file formats set.

**Comment by ds-sloth** [comment]
I'm confused about why the game is attempting to load from the directory /3ds/thextech/ instead of from an installed asset pack (either packed at /3ds/thextech/aod.romfs or extracted -- much slower -- to the directory /3ds/thextech/assets/aod/).

**Comment by Trickiy** [comment]
I used the thextech-adventure-of-demo-assets-full.7z extracted it and put the 3dsx in the root of the folder.

**Comment by ds-sloth** [comment]
TheXTech doesn't care where the 3dsx file is; instead, you need to install the assets-aod.romfs file into the /3ds/thextech/ folder (absolute path).

**Comment by Trickiy** [comment]
This issue is just me being a idiot so I am going to close this and give a real issue.
