### ISSUE TITLE
Adventure of Demo level 1 loads too slow

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#786]
On 3ds loading some of the levels are just slow enough to convince me that the 3ds has crash while others are fast.

**Comment by Wohlstand** [comment]
Please try the special version of the [gamepack optimized for 3DS](https://builds.wohlsoft.ru/3ds/assets-aod-3ds.zip) (it's available just here: https://github.com/TheXTech/TheXTech/wiki/Game-assets-packages#adventures-of-demo). All that you need is unpack the content of archive, put the file at the `/3ds/thextech/` directory and rename the file into `assets.romfs`. The raw game pack (the general pack for all platforms) requires extra resources to prepare resources and convert textures into native 3DS's format (not just decoding to RGBA and supplying to the graphics API, 3DS requires a special colour format that needs an extra work to get it here). Additionally, the file system of SD card is pretty slow, and ROMFS pack allows to partially escape this.

**Comment by ds-sloth** [comment]
Also note that you don't need to place the package specifically at assets.romfs -- any filename ending with romfs will be acceptable. You can take advantage of this to have multiple asset packs installed at once, and then switch between them by holding the select key at the main menu.

**Comment by Wohlstand** [comment]
Oh, ye, forgot that's with the latest dev-version that's possible, but the stable version requires the fixed filename right now.

**Comment by Trickiy** [comment]
I still in counter the slow load times with the opimized romfs and latest devel this is most likely a bug.

**Comment by ds-sloth** [comment]
Okay, thank you for testing. I will try to take a look at this with some debugging tools tomorrow to understand which procedures are taking it so long (and why they aren't affected for the other asset packs you've tested).

**Comment by ds-sloth** [comment]
This was caused by some expensive logic in the format detection code in SDL MixerX (and some inefficient logic in the SDL and 3DS standard libraries).

The fix was relatively complicated but it should also be working now. Once tonight's build is ready, please test it and check if the problem is resolved.

**Comment by Trickiy** [comment]
Seems to be working normally now, but I wanna test more throughly after school to make sure no other levels are affected.

**Comment by Trickiy** [comment]
The problemis resolved.

**Comment by Wohlstand** [comment]
Just as a note: the same problem appears on Wii U too, so, I debugged it on my Wii U actually xD.
