### ISSUE TITLE
Choose assets on launch softlock

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#787]
### Describe the issue

When I enable choose assets on launch exit then reopen the game will get stuck, but I still can go to the home menu.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#e4cc5fd

### Platform

3DS

### Processor architecture

None

**Comment by ds-sloth** [comment]
I have a good idea of why this is; it's actually closely related to #781. I'll try to fix this tonight. Thanks for your patience!

**Comment by ds-sloth** [comment]
This should be fixed now. Please let me know if a new build from tonight works better for you (once it is ready).

**Comment by Trickiy** [comment]
Fixed.
