### ISSUE TITLE
misaligned editor curser

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#789]
### Describe the issue

When I try to place a tile on the world map the tile will be placed 1 tile to the right instead of the center.
![image](https://github.com/user-attachments/assets/5accdd35-366d-4041-bd90-01a4484bd096)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#e4cc5fd

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Thanks for the report! I've confirmed this bug and also confirmed that it appears specific to the 3DS world map editor. I will try to resolve it ASAP but it is lower priority than the other two bugs you reported recently.

**Comment by Trickiy** [comment]
Ok I'll wait.

**Comment by ds-sloth** [comment]
This should be fixed now, please confirm at your convenience.

**Comment by Trickiy** [comment]
World map curser misalignment issue is fixed but with a new one taking its place.
![image](https://github.com/user-attachments/assets/fec819d7-7a76-4820-a0ee-6035dfffbfb2)

**Comment by ds-sloth** [comment]
Thanks for the report regarding the level cursor in #791. I think you are right about this and I have an idea of how I introduced that bug (the world and level logic are different, but I didn't separate them here).

**Comment by ds-sloth** [comment]
Alright, I'm about to call it a night but wrote this attempted fix on my phone. I hope it works for you, otherwise I'll fix this in the morning for me. Thanks!

**Comment by Trickiy** [comment]
Tested working as intended.
