### ISSUE TITLE
Exiting the level editor breaks things.

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#790]
### Describe the issue

When I enter the level editor then save and exit the the title screen looks like this:
![image](https://github.com/user-attachments/assets/9c603b3e-4214-4a54-b691-e3e9069c140e)
When I try to enter any episode not just custom the scream looks like this: 
![image](https://github.com/user-attachments/assets/da599156-f910-4f55-bd06-93dabb68d8e4)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#28ca69c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by Trickiy** [comment]
Forgot to mention the bug can be transfered from one assets pack to another.

**Comment by ds-sloth** [comment]
Lastly, this one should be fixed too. Please give it a try.

**Comment by Trickiy** [comment]
This is now working as expected.
