### ISSUE TITLE
Add option to disable editor out of bounds flashing

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#792]
Apon disabling the flash it will stay gray because some may find it annoying.

**Comment by Wohlstand** [comment]
Actually, I would just draw a semi-transparent gray filter here that conversion everything out of section like Moondust Editor does.

**Comment by ds-sloth** [comment]
This is a good idea and easy to implement, I'll plan to take care of it tomorrow.

**Comment by Trickiy** [comment]
After taking a look I like how the blocks are partially grayed out saying this will not be visible, even though it's not intended.
![image](https://github.com/user-attachments/assets/5785141a-0911-4490-a31f-0ede9c9157b3)

**Comment by ds-sloth** [comment]
Thanks for the test! The blocks being partially grayed out is intended, but the gap between where the background and the foreground get grayed out is not ideal (but, it only affects the 3DS). Still, I think we can close this issue. There's nothing more to do here until we complete the background2 overdraw system.

**Comment by Trickiy** [comment]
I think closing is fine since the issue is already open in [#753](https://github.com/TheXTech/TheXTech/issues/753).
