### ISSUE TITLE
vertical & horizontal wrong wrap

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#793]
### Describe the issue

When I have a level like this with horizontal & vertical wrap enabled, 
![image](https://github.com/user-attachments/assets/49b61e20-b2c5-41a6-8ea7-7c50496cea40)
without any out of bounds blocks the gumbas or any other enemy will teleport upwards. 

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#29ca69c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Are you referring to this?
<img src="https://github.com/user-attachments/assets/327767fb-74f4-4252-b16e-71994a18b118" width="640" height="360">

If so, this is a well-known vanilla bug and the solution is to extend the floor one tile on either side of the screen.

**Comment by Trickiy** [comment]
Yes that's the same bug I was talking about, didn't know it was such a well known bug but now I know. I won't be suprised if I report something already well known again.

**Comment by ds-sloth** [comment]
Don't worry about it, I'd always prefer to get extra reports than to not learn about an issue. This one has an easy enough fix that we aren't planning to change it, just remember to extend your platforms if you wrap the level.

There's a few other things that can happen with level wrap that we're aware of here: #75

**Comment by ChristianSilvermoon** [comment]
I could see a pretty useful use of this behaviour, actually :thinking:
