### ISSUE TITLE
Screen size smbx (wide) shows out of bounds

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#797]
### Describe the issue

When I have the screen size smbx (wide) on the right side of the screen I see outside of what should be visible.
![image](https://github.com/user-attachments/assets/9bd0680c-dbc6-44b7-b7ce-621c6fcc4807)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#7320e26

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by Trickiy** [comment]
One nice thing about this bug is that I get to see the gumbas fall off screen.
![image](https://github.com/user-attachments/assets/c80622ae-0c91-42fd-8b2d-cf3182c81d92)
HD has the same issue and most likely other resolutions.

**Comment by ds-sloth** [comment]
Thanks for the report! Please give the next build a try.

**Comment by Trickiy** [comment]
No problem, and the bug is fixed.
