### ISSUE TITLE
Walking under springs on slopes closes springs

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#800]
### Describe the issue

When I use this setup and walk under the spring, the spring closes.
![image](https://github.com/user-attachments/assets/29814020-8ed4-45e7-b1c7-e6de4d9a5d35)

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#e5746e6

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Please don't stop reporting these cases -- they are very useful for us to track! -- but also don't be surprised when we close them directly.

If you are interested to see which types of vanilla bugs we fix, there should be a section called "types of bugs" in our wiki (maybe under the article considerations for contributors?).

**Comment by Trickiy** [comment]
>If you are interested to see which types of vanilla bugs we fix, there should be a section called "types of bugs" in our wiki (maybe under the article considerations for contributors?).

Ok I will look at the wiki in the morning.

>Please don't stop reporting these cases

I wasn't planning to stop.
