### ISSUE TITLE
Entering editor then trying to close via home menu will never finish closing

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#801]
### Describe the issue

When I enter the editor and exit to the homemenu and close the application it will never close. I only do this when I don't care about losing my data linked to the editor.

### A type of bug

Native bug, non-desktop, editor

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#e5746e6

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
This sounds like something is going quite wrong on the internals. I'll verify it in the morning and then try to fix. Thank you!

**Comment by ds-sloth** [comment]
Sorry to take so long on this one. I've given it a good try and I think that it should be fixed now. Please confirm on your side!

**Comment by Trickiy** [comment]
> Sorry to take so long on this one. 

It's okay I haven't been using the editor much just been enjoying what already exists.

**Comment by Trickiy** [comment]
It now closes.
