### ISSUE TITLE
Mario enters pipe when on the right side of a frozen pirana

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#804]
### Describe the issue

When you have a setup like this
![image](https://github.com/user-attachments/assets/d676571c-b944-4d8c-9100-68f6135013e9)
Mario will go thru the pipe, but when on the other side 
![image](https://github.com/user-attachments/assets/a150be0e-1c42-4536-91f9-992b7d1e0638)
Mario will not go down the pipe.

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Random, Often

### Version

1.3.7-dev

### Version Hash

#1c43287

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Fun! Thanks for finding this. I replicated it locally, here: [frozen-plant-warp.lvl.zip](https://github.com/user-attachments/files/16666808/frozen-plant-warp.lvl.zip)

For these pure vanilla bugs, you are welcome to not fill out the full bug form if it's inconvenient for you. The most important thing is the screenshot and the description. Thank you!

**Comment by Trickiy** [comment]
I will continue to use the full bug form just so the chance of me forgetting is non existent. Plus I want to stay in a good habit, thanks for the option though.

**Comment by SkullGamer205** [comment]
> I will continue to use the full bug form just so the chance of me forgetting is non existent. Plus I want to stay in a good habit, also if you recall I have not played the original smbx 1.3 so I still don't truly know if it is native or not. Thanks for the option though.
> 
> >I replicated it locally, here: [frozen-plant-warp.lvl.zip](https://github.com/user-attachments/files/16666808/frozen-plant-warp.lvl.zip)
> 
> I will look at the level you made at some point.

But you can download SMBX 1.3 anytime, and test bugs...

**Comment by Trickiy** [comment]
> But you can download SMBX 1.3 anytime, and test bugs...

Yes true if I had a windows PC I could do true vanilla smbx testing. But I do not have a windows PC or Linux, I am stuck with a overly restricted school chromebook and my free 2ds xl. As why I do not use vanilla SMBX I could if I would, when I am able to obtain a computer I will. Finally sorry for the late reply.
