### ISSUE TITLE
Add Thextech to Universal updater?

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#809]
I would like to ask if it would be okay if I requested for thextech both stable and devel builds to be added to Universal updater for 3ds? I think this will be very convenient for all 3ds users, and make people that would be interested in the project aware of this. I don't think anything would need to be changed.

**Comment by ds-sloth** [comment]
You're welcome to do this, but please only add the development build, and please mark it as alpha software. 1.3.6.5-stable for 3DS has a number of severe known issues and 1.3.6.6-dev doesn't fix all of them. Once 1.3.7-stable has been released, then we can start hosting separate stable and development branches on 3DS.

And please ping me in any Discord or GitHub messages. Thanks!

**Comment by Trickiy** [comment]
@ds-sloth Thanks for permission I will be adding the dev build, but I am not able to make a icon to be viewed in universal myself could you help?

**Comment by Trickiy** [comment]
Thanks, I wanna make sure I am not missing anything or if you want me to add anything to my request could you check?
[Screen recording 2024-08-27 8.42.15 PM.webm](https://github.com/user-attachments/assets/268a844d-5976-419c-b304-363ffcdbac15)

**Comment by ds-sloth** [comment]
Be sure to include our repository URL, and link to our GitHub wiki for extra info (as well as https://builds.wohlsoft.ru/3ds/ for asset downloads).
