### ISSUE TITLE
Jagged visuals

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#810]
### Describe the issue

At times the visuals will look more jagged,
![2024-08-28_20-31-30 573_top](https://github.com/user-attachments/assets/3bf6dc0e-d31b-4866-9fe9-434ac144f110)
after I change the resolution it looks normal.
![2024-08-28_20-31-48 796_top](https://github.com/user-attachments/assets/fdd14ac2-0971-4a11-b9aa-808118ea0275)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Happens randomly, often

### Version

1.3.7-dev

### Version Hash

#74d00a3

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

### Log file (if presented)

[TheXTech_log_2024_08_28_20_22_31.txt](https://github.com/user-attachments/files/16790366/TheXTech_log_2024_08_28_20_22_31.txt)

**Comment by ds-sloth** [comment]
Hi, I actually couldn't reproduce this issue locally, but I've rewritten the code to enable linear filtering earlier in the initialization process. Can you please see if the most recent commit helps? Thanks!

**Comment by Trickiy** [comment]
I think the most recent commit did the trick cause I am no longer having linear filtering automatically remove it's self.

**Comment by ds-sloth** [comment]
Great!
