### ISSUE TITLE
Yoshi duplication

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#811]
### Describe the issue

While I was playing "The Invasion 2" 
![2024-08-29_07-56-57 528_top](https://github.com/user-attachments/assets/12d8668d-b43d-47f9-a621-66a54a1dc611)
I managed to do some ace or something and got the purple yoshi to duplicate.
![2024-08-29_07-56-18 819_top](https://github.com/user-attachments/assets/ee66d047-b45c-46f5-bf1e-adf482e0c64e)

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Happens randomly, rare

### Version

1.3.7-dev

### Version Hash

#a93ba14

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

### Log file (if presented)

[TheXTech_log_2024_08_29_07_41_13.txt](https://github.com/user-attachments/files/16798719/TheXTech_log_2024_08_29_07_41_13.txt)

**Comment by ds-sloth** [comment]
No, this is totally my mistake. Sorry about that. Please confirm that it is fixed now.

**Comment by Trickiy** [comment]
I was about to say it was native after testing for a while because it was so consistent.  I am going to test now.

**Comment by Trickiy** [comment]
Fixed
