### ISSUE TITLE
Custom episodes & levels have bad performance

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#812]
### Describe the issue

I downloaded the custom episode Super Mario Forever from the archive, and it seems to stutter and freeze for at seemingly at random when in a level or in the world and in the editor. The level [Cool SMB3 Vocano](https://www.youtube.com/watch?v=teY0uMfvkeg) by Vitzie629's Gaming & Technology has a long freeze when I hit the freeze block. It's possible that all Vitzie629's levels lag, stutter, or freeze.

### A type of bug

Compatibility bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#f7060c0

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Did you convert the episode? Or at least pack it?

If not, this is a known issue with the 3DS hardware and can't be helped unfortunately. The conversion code is currently difficult but we are planning (1) a better Moondust conversion tool, and (2) an online repository of converted episodes for you to download.

In the meantime, if you have specific episodes you want me to convert for you, please connect over Discord or Matrix and I can do so.

**Comment by Trickiy** [comment]
>In the meantime, if you have specific episodes you want me to convert for you, please connect over Discord or Matrix and I can do so.

Thanks I can access discord but I don't know which thread I should use.

**Comment by ds-sloth** [comment]
smbx-zone is fine.

**Comment by Trickiy** [comment]
Ok thanks I won't asking for anything for now due to it being late, but tomorrow after noon maybe.
