### ISSUE TITLE
asxt & a2xt don't load all assets

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#815]
### Describe the issue

When I try to load the packs I get a error and the inabillaty to play the episodes.
![2024-09-01_21-45-19 656_bot](https://github.com/user-attachments/assets/bd1b9605-ae62-410b-a1dd-8deac0bb9845)

### A type of bug

Compatibility bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8a135c5

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

### Log file (if presented)

[TheXTech_log_2024_09_01_22_27_02.txt](https://github.com/user-attachments/files/16831642/TheXTech_log_2024_09_01_22_27_02.txt)

**Comment by ds-sloth** [comment]
I can't reproduce this on my side. Can you please retry?

**Comment by Trickiy** [comment]
Maybe it didn't download correctly on my side will redownload.

**Comment by ds-sloth** [comment]
Great. It's possible that was affecting your experience in Lowser's Conquest as well (but note, even a perfectly converted version of that still has some texture size issues).

**Comment by Trickiy** [comment]
>(but note, even a perfectly converted version of that still has some texture size issues).

Noted.
