### ISSUE TITLE
Collecting all Bishoujo Pics won't open the star door

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#818]
### Describe the issue

In Lowsers Conquest sometimes after dying collecting all of the Bishoujo Pic will not open the star door at the end of the level. 
<-- Happens randomly,rare  Also since this is similar, after collecting a rainbow star then dying and respawning at the check point. All Bishoujo Pics collected after the checkpoint will be missing in that specific level.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8267f3c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by Superbloxen** [comment]
That may be a normal thing with SMBX, Dragon Coins don't save at checkpoints, The only items that save states between deaths are Checkpoints and the SMW-Styled Star (the rainbow star).

**Comment by Wohlstand** [comment]
This is actual behaviour of engine as any objects except of stars, weren't remembered and gets never erased on restart (including checkpoints), same as SMBX 1.3 was. And to make them not appear, it's required to implement an extra script to make their disappearence being remembered in the future.

**Comment by Trickiy** [comment]
So should this be closed due to being a vanilla thing.

**Comment by ds-sloth** [comment]
That's correct, this is actually not a bug but the intended behavior in SMBX 1.3 and TheXTech. You need to collect all the coins during a single life to collect the prize (but the game will track the coins you have collected even if it takes multiple lives).

You can tell if you collected a coin in the current life by checking whether it is sparkling in the indicator on the top right of the screen.
