### ISSUE TITLE
Lowsers Conquest: broken enemie death animations

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#820]
### Describe the issue

When some enimes die the animation is buggy looking or missing a part of its sprite.
![2024-09-03_19-51-22 981_top](https://github.com/user-attachments/assets/9ee0207c-8298-4034-a81b-99d9d055c80c)
![2024-09-03_19-52-20 910_top](https://github.com/user-attachments/assets/511511e3-0399-4dc7-a634-34ed5e106cd1)
![2024-09-03_19-52-28 275_top](https://github.com/user-attachments/assets/f6b660e8-388c-4bc9-a96a-59ee0257fb8d)
![2024-09-03_19-52-51 928_top](https://github.com/user-attachments/assets/cb030d31-059e-4867-af1e-8649ff44e5d5)
![2024-09-03_19-52-55 320_top](https://github.com/user-attachments/assets/1e4fd7c4-e0f2-4b32-894f-a095fed0f4c2)
![2024-09-03_19-53-37 860_top](https://github.com/user-attachments/assets/7615815e-f902-4fce-84e4-9f32f55c08e6)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8267f3c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Thank you for finding this! I recently noticed something similar on Wii but didn't know it affected 3DS as well. I'll try to track the cause down later this week.

**Comment by ds-sloth** [comment]
I think that this should be fixed now. Please give it a try!

**Comment by Trickiy** [comment]
All enemie death animations look as intended.
