### ISSUE TITLE
2 batteries instead of 1

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#821]
### Describe the issue

In the image there should only be one battery in the top right corner, but there's a second one at the bottom left corner that can block things.
![2024-09-03_19-51-22 981_top](https://github.com/user-attachments/assets/9ee0207c-8298-4034-a81b-99d9d055c80c)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1..3.7-dev

### Version Hash

#8267f3c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
I'll disable the controller battery display by default on keyboard, touchscreen, and 3DS.

In the meantime you can get the behavior you are looking for by going to your controls profile's settings and disabling the battery display option.

**Comment by Wohlstand** [comment]
The second battery indicator supposed to be the battery of the controller. On 3DS/Vita this thing seems useless if the built-in controller is used. On console-like Android devices such as Retroid Pocket this is also useless until any custom Bluetooth or wired controller gets plugged/paired.

**Comment by ds-sloth** [comment]
I think as a rule, it's probably good to enable this by default for Wiimote and SDL joysticks / game controllers, and disable for everything else.

**Comment by Wohlstand** [comment]
Sounds a good idea: SDL actually reports does controller have a battery or not, and Wiimote is the only controller that is used via OGC directly rather than via SDL2.

**Comment by ds-sloth** [comment]
Please let me know if this works as expected. The option to display controller battery status should be gone now on 3DS (and keyboard and touchscreen in the SDL2 builds).

**Comment by Trickiy** [comment]
The battery display is now gone.
