### ISSUE TITLE
Lowsers Conquest: Corrupt minecart hint

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#823]
### Describe the issue

in the hint the minecart is glitchy.
![2024-09-04_17-14-39 858_top](https://github.com/user-attachments/assets/2712d716-2f5c-4cbf-bfa7-5e3bb93d43e6)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8267f3c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by Wohlstand** [comment]
Because the shell had been customized so much, to turn it into the railcar, and that was done tricky

**Comment by Trickiy** [comment]
So fixing this will be tricky too?

**Comment by ds-sloth** [comment]
Please let me know at your convenience if this has been fixed.

**Comment by Trickiy** [comment]
Looks the way I would expect.
![2024-09-05_15-54-19 660_top](https://github.com/user-attachments/assets/3b7d3795-c81e-4a91-a62a-9c145d959e11)
