### ISSUE TITLE
Player can hold item after its layer is hidden

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#824]
### Describe the issue

In the level Mysterious Pipe when the following text box appears while Mario is holding a block it will dissapear then your holding a invisible block.
![2024-09-04_17-27-14 768_top](https://github.com/user-attachments/assets/6bde688f-9ee1-4468-8c44-fd2b9f9ac5ea)

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#8267f3c

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Thanks a lot for documenting this! I've reproduced it on my side. I don't think it's necessary to fix it but it's good to be aware of it.

**Comment by Shadowblitz16** [comment]
@ds-sloth the intended behavior seen in the redigit's airship battle level is the item disappears and Mario stops holding it.

**Comment by ds-sloth** [comment]
If you look carefully at the screenshot and at the battle in question, you will notice that the battle level actually has exactly the same strange behavior.

The player keeps their holding frame after the layer disappears and until they release the Run button.

**Comment by Shadowblitz16** [comment]
> If you look carefully at the screenshot and at the battle in question, you will notice that the battle level actually has exactly the same strange behavior.
> 
> The player keeps their holding frame after the layer disappears and until they release the Run button.

Oh your right!
