### ISSUE TITLE
Yoshi clip

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#825]
### Describe the issue

Go to a level like Megaton Vase Hole and crouch jump in the spot in the image and you'll screen wrap to the other side.
![2024-09-05_15-46-53 189_top](https://github.com/user-attachments/assets/8035c33e-0697-407e-bd37-fce671277f10)
![2024-09-05_15-47-06 696_top](https://github.com/user-attachments/assets/ce858e59-a1b5-4e3a-8b2f-4b01b13bd18b)

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#590838a

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
I'm pretty sure that this is just a level peculiarity. The "zipping" behavior that occurs when the player unducks while there is a ceiling above them is a well-known feature of the SMBX physics. (We wouldn't even call it a bug!)

Is that what is happening here?

**Comment by Trickiy** [comment]
Yes I was unducking when under a block to wrap around to the other side of the level.

**Comment by ds-sloth** [comment]
Cool! This is actually a well-known behavior, it's even mentioned in the tutorial of Yoshi's Archipelago.

![Scr_2024-09-05_18-00-19](https://github.com/user-attachments/assets/ea8923b0-7cb1-4b23-84f7-b566acc97346)
