### ISSUE TITLE
Disabling v-sync makes everything run twice as fast

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#831]
### Describe the issue

I disabled v-sync to see if it would improve the performance, and then the game started running double the intended speed. I think this should be a feature in some form.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#590838a

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
You're right that if you disable V-Sync and enable Unlimited Framerate, the game will run around 130 FPS on 3DS. That is "a feature in some form", as you noted, and we already have it.

I should also mention that if you disable V-Sync and *don't* enable Unlimited Framerate, then the game will run at 65 FPS, which is the original framerate of SMBX 1.3.
