### ISSUE TITLE
Lethal boot clip

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#832]
### Describe the issue

In AoD the level Shell Hell, if you enter the bag while spin jumping while next to the wall you'll clip into the wood above you.
![2024-09-08_21-10-54 761_top](https://github.com/user-attachments/assets/c4ba6c52-8892-40f7-9aaf-1713d358eba7)
![2024-09-08_22-02-53 538_top](https://github.com/user-attachments/assets/a36373b0-38d4-43be-8f8d-d98fabb1cd3c)

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Happens always

### Version

1.3.7-dev

### Version Hash

#590838a

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by Trickiy** [comment]
I made a mini level with this bug. 
[Escape artist.zip](https://github.com/user-attachments/files/16935682/Escape.artist.zip)

**Comment by ds-sloth** [comment]
This is a fun bug. Totally vanilla. Also (interestingly) it only seems to work when the player is next to a wall to their right. Thanks for the report!
