### ISSUE TITLE
Inaccurate checkpoints

### ISSUE THREAD

**Issue by Trickiy** [TheXTech/TheXTech#835]
### Describe the issue

In Lowsers Conquest the level Cowards Airship, the checkpoint respawan point is in the upper area of checkpoint instead of being on the platform.
![2024-09-12_19-56-23 865_top](https://github.com/user-attachments/assets/4d9c2ebe-e4a5-4b04-8e48-5652880d09fb)

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.7-dev

### Version Hash

#fc5470d

### Platform

3DS

### Processor architecture

ARM32 / ARMv7 (32-bit ARM)

**Comment by ds-sloth** [comment]
Thanks for the report! I *think* that this is a vanilla bug caused by the fact that the checkpoint overlaps a semisolid block -- the place the player spawned looks like it would be the top of the block. I'll try to confirm soon.

**Comment by ds-sloth** [comment]
I have now had a chance to check this, and it is a very classic vanilla bug. It's the fault of Lowser for not testing this one.
