### ISSUE TITLE
[Nintendo Switch] Game crashes the moment it opens on Nintendo Switch

### ISSUE THREAD

**Issue by ltecheroffical** [TheXTech/TheXTech#836]
### Describe the issue

When opening the game on Switch from the HB Menu, it shows a black screen and closes. No errors, no nothing.

### A type of bug

Not specified

### Does this issue happens always or randomly?

Always happens

### Version

v1.3.6.5

### Platform

Switch

### Processor architecture

ARM64 / AARCH64 (64-bit ARM)

**Comment by Wohlstand** [comment]
Looks weird... I'll try to take a look soon. For now I am too busy.

**Comment by ds-sloth** [comment]
Did you copy any assets? If so, where did you install them? Do you have any log files you can share with us (probably at `/TheXTech/logs`)? Thanks!

**Comment by ltecheroffical** [comment]
> Did you copy any assets? If so, where did you install them? Do you have any log files you can share with us (probably at `/TheXTech/logs`)? Thanks!

All I did was copy the .nro file to /switch

**Comment by ds-sloth** [comment]
Alright, then you also do need to install an asset pack. You can find instructions to do so on our GitHub wiki or in the download section on https://wohlsoft.ru

**Comment by ltecheroffical** [comment]
The asset pack fixed it

**Comment by Wohlstand** [comment]
... I probably should implement custom message boxes to be able to print errors in any way to avoid such cases in future.
