### ISSUE TITLE
Hardcoded minimal font

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#840]
For error messages on various platforms and for future purposes, it will be nice to add a hardcoded font that can be used for messages and text entry without any external dependencies. I'll try to implement this before our major 1.3.7.x release. My main concern will be keeping the executable size low (this is especially important on our minimal homebrew ports).

I will probably implement this by adding a raster font 0 and a `XRender::loadHardcodedFont(StdPicture&)` method.

**Comment by ds-sloth** [comment]
See #836 and #845 for examples where this would have been helpful.

**Comment by ds-sloth** [comment]
Wohlstand, I've tested this on PC and some homebrew platforms. Can you please test the no-assets error screen on Wii U whenever convenient (before the v1.3.7 release)? Thanks!

**Comment by Wohlstand** [comment]
I'll try tomorrow.

**Comment by Wohlstand** [comment]
On Wii it just works:
![2024-10-22_18-16-30](https://github.com/user-attachments/assets/f31fb342-8fcf-4bbc-bf9d-525491ce5c91)

On Wii U works, but it stucks, I can't quit it at all:
![2024-10-22_18-43-43](https://github.com/user-attachments/assets/4af99f1e-1ca4-46bc-ae79-3becef401a06)
(I used WiiU GamePad)

**Comment by Wohlstand** [comment]
Okay, forgot to say that everything with this is completed, can be just closed.
