### ISSUE TITLE
Vine-head can be pushed by walking NPC with block top

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#841]
### Describe the issue

A vine-head's horizontal speed will be set by a walking NPC below it, resulting in vines that are not perfectly vertical.

### A type of bug

Vanilla bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.5 to 1.3.7-dev

### Platform

Linux

### Processor architecture

x86_64 / x64 (64-bit x86)

### Example Case

level34.lvl from The Invasion 2, shortly after the first screen.

### Recording

![Scr_2024-09-29_15-11-26](https://github.com/user-attachments/assets/0d1b4b69-83a9-4b39-9df9-0cd307709e18)

**Comment by Superbloxen** [comment]
When thrown, Vine Heads will also make a diagonal trail.

**Comment by ds-sloth** [comment]
Not exactly, this is fine to make in SMBX, but creators can be aware of this unexpected behavior.

More importantly, I want us to document all of the unexpected behaviors in SMBX so that we can remember which bugs are vanilla and which are native without needing to repeat our testing.

**Comment by Wohlstand** [comment]
At the "Prelude to the stupid" it's the "Terrible level" where is possible to grub a head from the grass and drop it by diagonal trajectory and it build the path.
