### ISSUE TITLE
Game selection screen notices

### ISSUE THREAD

**Issue by Wohlstand** [TheXTech/TheXTech#844]
Hello!

During various tests and experiments, I have some notices, and to don't lose them, I making this issue as a reminder for everybody.

- [x] On consoles and when game is not selected by command like arguments, it's better to show the game selection screen by default.
- [x] Always fade-out screen when selecting any game in the list for a first time after startup, and play short visual animation when opened this menu via DROP button hold. On weak devices, it's a bit annoying that when you select a game, it just hangs for a short time without any visual signs that "I accepted your selection, now going to load it..." until it shows the loading screen of the game.
- [ ] Additionally, when running a level test via external file opening (command line argument, or system event on macOS and Android), would be cool to implement the manual character selection menu (at least without choising the initial power up or mount) when no command line arguments specified anything.

These moments (if not count the third) are very important to be done close to the stable release, and just note them as known issues at the possible beta release.

**Comment by ds-sloth** [comment]
Triage: I think that item (2) at the launcher screen is the highest priority here, followed by (1) on consoles. I think the rest of the cases can probably wait until after 1.3.7.

**Comment by ds-sloth** [comment]
An additional case: on first run of the engine it should be necessary to show the menu if more than one asset pack is present.

**Comment by ds-sloth** [comment]
(1) and (2) should be done!

**Comment by Wohlstand** [comment]
I'll try some as soon as I'll come to my home.

**Comment by Vinicin2** [comment]
Sou um usuário da versão de desenvolvimento do thextech 1.3.7, e sempre acompanhando o trabalho de vocês, e estão de parabéns, só uma dúvida, sabe me dizer se a versão 1.3.7 vai ser lançado para este ano?

**Comment by Wohlstand** [comment]
> Sou um usuário da versão de desenvolvimento do thextech 1.3.7, e sempre acompanhando o trabalho de vocês, e estão de parabéns, só uma dúvida, sabe me dizer se a versão 1.3.7 vai ser lançado para este ano?

Wrong place to ask such questions... Make the discussion topic please. Don't be shy to use translator to understand us.

**Comment by Vinicin2** [comment]
> > Sou um usuário da versão de desenvolvimento do thextech 1.3.7, e sempre acompanhando o trabalho de vocês, e está de parabéns, só uma dúvida, sabe-me dizer se a versão 1.3.7 vai ser lançada para este ano?
> 
> Lugar errado para fazer essas perguntas... Você fez um off-topic. Crie o tópico de discussão, por favor. Não tenha vergonha de usar o tradutor para nos entender.

Muito obrigado, pode deixar, sou do Brasil, irei criar sim.

**Comment by Wohlstand** [comment]
(1) and (2) were tested several times a while ago. The only item left is (3).

**Comment by Wohlstand** [comment]
Anyway... that should be done as a separate task.

**Comment by ds-sloth** [comment]
Continued in #873
