### ISSUE TITLE
Never opened (Wii)

### ISSUE THREAD

**Issue by StevMC1289** [TheXTech/TheXTech#845]
### Describe the issue

every time I tried to simply open the game, it never opened. it just went to a black screen for a second or two, then back to the homebrew channel. I have no clue what happened. 

### A type of bug

Compatibility bug

### Does this issue happens always or randomly?

Always happens

### Version

v1.3.6.6

### Platform

Wii

### Processor architecture

PPC32 (32-bit Power PC with Big-Endian)

### Log file (if presented)

[TheXTech_log_2024_10_19_10_08_57.txt](https://github.com/user-attachments/files/17445511/TheXTech_log_2024_10_19_10_08_57.txt)
[TheXTech_log_2024_10_19_10_08_41.txt](https://github.com/user-attachments/files/17445512/TheXTech_log_2024_10_19_10_08_41.txt)
[TheXTech_log_2024_10_19_10_08_31.txt](https://github.com/user-attachments/files/17445513/TheXTech_log_2024_10_19_10_08_31.txt)
[TheXTech_log_2024_10_19_10_08_19.txt](https://github.com/user-attachments/files/17445514/TheXTech_log_2024_10_19_10_08_19.txt)
[TheXTech_log_2024_10_19_10_08_09.txt](https://github.com/user-attachments/files/17445515/TheXTech_log_2024_10_19_10_08_09.txt)
[TheXTech_log_2024_10_19_10_07_58.txt](https://github.com/user-attachments/files/17445516/TheXTech_log_2024_10_19_10_07_58.txt)
[TheXTech_log_2024_10_19_10_07_48.txt](https://github.com/user-attachments/files/17445517/TheXTech_log_2024_10_19_10_07_48.txt)
[TheXTech_log_2024_10_19_10_07_38.txt](https://github.com/user-attachments/files/17445518/TheXTech_log_2024_10_19_10_07_38.txt)
[TheXTech_log_2024_10_19_10_07_28.txt](https://github.com/user-attachments/files/17445519/TheXTech_log_2024_10_19_10_07_28.txt)
[TheXTech_log_2024_10_19_10_07_17.txt](https://github.com/user-attachments/files/17445520/TheXTech_log_2024_10_19_10_07_17.txt)
[TheXTech_log_2024_10_19_09_58_55.txt](https://github.com/user-attachments/files/17445521/TheXTech_log_2024_10_19_09_58_55.txt)
[TheXTech_log_2024_10_19_09_58_45.txt](https://github.com/user-attachments/files/17445522/TheXTech_log_2024_10_19_09_58_45.txt)
[TheXTech_log_2024_10_19_09_58_35.txt](https://github.com/user-attachments/files/17445523/TheXTech_log_2024_10_19_09_58_35.txt)
[TheXTech_log_2024_10_19_09_58_16.txt](https://github.com/user-attachments/files/17445524/TheXTech_log_2024_10_19_09_58_16.txt)
[TheXTech_log_2024_10_19_09_58_04.txt](https://github.com/user-attachments/files/17445525/TheXTech_log_2024_10_19_09_58_04.txt)
[TheXTech_log_2024_10_19_09_57_54.txt](https://github.com/user-attachments/files/17445526/TheXTech_log_2024_10_19_09_57_54.txt)
[TheXTech_log_2024_10_19_09_57_44.txt](https://github.com/user-attachments/files/17445527/TheXTech_log_2024_10_19_09_57_44.txt)
[TheXTech_log_2024_10_19_09_57_04.txt](https://github.com/user-attachments/files/17445528/TheXTech_log_2024_10_19_09_57_04.txt)
[TheXTech_log_2024_10_19_09_56_47.txt](https://github.com/user-attachments/files/17445529/TheXTech_log_2024_10_19_09_56_47.txt)
[TheXTech_log_2024_10_19_09_56_36.txt](https://github.com/user-attachments/files/17445530/TheXTech_log_2024_10_19_09_56_36.txt)
[TheXTech_log_2024_10_19_09_50_43.txt](https://github.com/user-attachments/files/17445531/TheXTech_log_2024_10_19_09_50_43.txt)
[TheXTech_log_2024_10_19_09_50_32.txt](https://github.com/user-attachments/files/17445532/TheXTech_log_2024_10_19_09_50_32.txt)
[TheXTech_log_2024_10_19_07_51_48.txt](https://github.com/user-attachments/files/17445533/TheXTech_log_2024_10_19_07_51_48.txt)
[TheXTech_log_2024_10_19_07_50_21.txt](https://github.com/user-attachments/files/17445534/TheXTech_log_2024_10_19_07_50_21.txt)
[TheXTech_log_2024_10_19_07_50_10.txt](https://github.com/user-attachments/files/17445535/TheXTech_log_2024_10_19_07_50_10.txt)

here are all 25 logs from every time I tried to open it. sorry if its a bother to add so many.

**Comment by ds-sloth** [comment]
Thanks for the email! You need to install an asset pack to the engine. You can do this by downloading the SMBX or Adventures of Demo assets packs from https://builds.wohlsoft.ru/wii/, and then extracting the folder to:

- v1.3.6.6: `sd:/thextech/`. When you are done, the engine should be able to find `sd:/thextech/gameinfo.ini`.
- v1.3.7-dev: `sd:/thextech/assets/<pack-name>/`. When you are done, the engine should be able to find `sd:/thextech/assets/<pack-name>/gameinfo.ini`.

The difference is because TheXTech v1.3.7 will support switching between asset packs in a single installation. Please let me know if this helps!

**Comment by StevMC1289** [comment]
am I supposed to put the contents of the assets folder inside `sd:/thextech`?

**Comment by StevMC1289** [comment]
it works, thanks for the help! :]
