### ISSUE TITLE
[Android Bug] Creating a long error message softlocks the game

### ISSUE THREAD

**Issue by Superbloxen** [TheXTech/TheXTech#847]
### Describe the issue

By creating a long error message with LunaDLL, the prompt that appears will go offscreen. On my device, there was no way to reach the OK button and unfreeze the game when the prompt appeared, rendering the game softlocked.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.6.6

### Platform

Android

### Processor architecture

None

**Comment by Wohlstand** [comment]
Can you make a very simple test level?
I think, I'll try to add a workaround here to force break these lines to make the message always fit to screen.

**Comment by Superbloxen** [comment]
Here is the file:

[softlocked.zip](https://github.com/user-attachments/files/17458870/softlocked.zip)

**Comment by Wohlstand** [comment]
One small note: the script `lunadll.txt` should be placed into custom directory, for the case the script is placed at same directory as level, it should be named `lunaworld.txt`.

**Comment by Wohlstand** [comment]
Actually, on desktop targets, such messages were true mess too:
![Снимок экрана от 2024-10-22 01-00-59](https://github.com/user-attachments/assets/5e7766a5-3ee5-492a-88f8-3e32e79e5727)
I think, for these lines I probably should just cut the length until print them in the error message.

**Comment by Wohlstand** [comment]
Okay, just now I did a small test, and on my phone it shows OK button, even it's small but still accessible. Please take the latest development version and try it in action.

**Comment by Superbloxen** [comment]
Tested, and this works normally on my end.

**Comment by Wohlstand** [comment]
Thanks for the confirmation!
Now I'll close this.
