### ISSUE TITLE
Main menu playstyle selection

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#852]
It will be nice to slightly polish the playstyle selection at the main menu:
* Use left/right instead of AltJump to switch (lets us remove "Alt Jump to Switch" text)
* Don't change any Config settings affecting the main menu's gameplay when mode is changed.

**Comment by ds-sloth** [comment]
I think this is done now but will leave the issue open during the v1.3.7 beta period for comments.

**Comment by LoveBodhi** [comment]
There's one unlocalized string "Make For" in the "editor" selection.

**Comment by ChristianSilvermoon** [comment]
Curious quesiton, but how will this affect the save slot page navigation from #664 If left/right changes play styles?


Is #664 still being considered?

**Comment by ds-sloth** [comment]
That's a very good question. This interference is actually the reason that #664 was never merged -- we were considering this feature for a very long time and held off on merging #664 for that reason.

The use case for 5 save slots is not obvious to me but if you can think of an alternative UI to get 5/6 save slots (while maintaining a good and consistent interface at resolutions down to 480x320) then I am open to implementing it.

**Comment by ds-sloth** [comment]
I'm closing this issue now; @ChristianSilvermoon's useful comments are still linked from the other PR.
