### ISSUE TITLE
Prevent editor lock-in

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#854]
On targets with no pointing device, it's possible to get locked in to the editor, with the only way to exit being restarting the engine.

To prevent this, I think that the default editor gamepad controls should be altered so that the left stick and D-Pad control the cursor by default, and the right stick controls scrolling. This would be controlled by a new gamepad option, "Swap sticks in editor".

(See also #702)

**Comment by ds-sloth** [comment]
I think this is done but will leave the issue open during the v1.3.7 beta period for comments on the new "Simple Editor Controls" option.

**Comment by 0lhi** [comment]
Works 👍

![Scr_2024-12-22_00-47-00_(1)](https://github.com/user-attachments/assets/7e28e01e-f372-4f05-af0a-0cdf2b49193f)
