### ISSUE TITLE
libopus: celt_pitch_xcorr_arm.s build failure (arm64 Linux target)

### ISSUE THREAD

**Issue by coreybruce** [TheXTech/TheXTech#855]
### Describe the issue

Hey there I just want to report that the latest version fails to build and complains about a subcommand

### Version

1.3.6.6

### Version Hash

8ab0ea0

### Build platform

Manjaro Linux Arm64

### Target platform

Linux

### Target processor architecture

Arm64

### Compiler name

cmake and Ninja

### Build log

Build Log:
https://gist.github.com/coreybruce/4c23544a07ea2635e9cab94b1bfbaa96

### What commands you typed in the terminal or what you did in your IDE?

Just the build commands from the documentation

**Comment by ds-sloth** [comment]
This has affected me also when making ARM Linux builds, but only around 1/3 of the time.

Perhaps there is some missed dependency in the build process.

Can you try building again from a clean build directory?

**Comment by coreybruce** [comment]
> This has affected me also when making ARM Linux builds, but only around 1/3 of the time.
> 
> Perhaps there is some missed dependency in the build process.
> 
> Can you try building again from a clean build directory?

Hey that's interesting to know also if you look at the build log I did a clean build :)

**Comment by ds-sloth** [comment]
I meant to ask if you could do another clean build, not reusing any of the intermediate files from your previous attempt.

**Comment by ds-sloth** [comment]
Wait a minute, this might not be random, it seems that I did a dumb workaround a while ago and forgot that my source directory was dirty.

**If you just want your build to work** please modify `3rdparty/AudioCodecs/libopus/CMakeLists.txt`. Find the line `if(OPUS_ARM_ASM AND CMAKE_COMPILER_IS_GNUCC)` (line 578 in my source). Modify it to read `if(0)` instead.

We will want to fix this issue but I'm not entirely certain what is causing this broken arm64 build yet.

**Comment by coreybruce** [comment]
> I meant to ask if you could do another clean build, not reusing any of the intermediate files from your previous attempt.

I have tried twice, originally was a git pull and then I deleted that and then I tried a clean build which is where this log came from just to make sure I didn't do anything wrong


>Wait a minute, this might not be random, it seems that I did a dumb workaround a while ago and forgot that my source directory was dirty.

>If you just want your build to work please modify 3rdparty/AudioCodecs/libopus/CMakeLists.txt. Find the line if(OPUS_ARM_ASM AND CMAKE_COMPILER_IS_GNUCC) (line 578 in my source). Modify it to read if(0) instead.

>We will want to fix this issue but I'm not entirely certain what is causing this broken arm64 build yet.

Oh alright I will do that and let you know how I go, thanks for letting me know :)  :+1:

**Comment by coreybruce** [comment]
So just to make sure I am correct I need to change that line to ```if(0)(OPUS_ARM_ASM AND CMAKE_COMPILER_IS_GNUCC)```

here is my output

```
FAILED: build.ninja 
/usr/bin/cmake --regenerate-during-build -S/mnt/PortableSSDDrive/projects/TheXTech/3rdparty/AudioCodecs -B/mnt/PortableSSDDrive/projects/TheXTech/build/external/AudioCodecs/src/AudioCodecs_Local-build
ninja: error: rebuilding 'build.ninja': subcommand failed
[2/327] Running utility command for git_version
=== git info: commit 8ab0ea08-dirty, branch main
[6/327] Building CXX object 3rdparty/a...ler/preprocessor/DirectiveParser.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by ds-sloth** [comment]
No, my apologies, the entire line should be `if(0)`

**Comment by coreybruce** [comment]
> No, my apologies, the entire line should be `if(0)`

Oh alrighty thanks for the clarifcation :smile: 

I build the Arm64 for the AUR package as there is no official Arm64 binary 

https://gitlab.com/linuxbombay/thextech
https://aur.archlinux.org/packages/thextech-bin

Would there be a official Arm64 binary in the future?

**Comment by ds-sloth** [comment]
Yes, we will have an official arm64 flatpak build as soon as GitHub makes arm64 runners free for open-source projects.

Possibly also AppImage depending on user demand.

**Comment by coreybruce** [comment]
Binary compiled!!! :tada: 

Awesome will we also get normal binaries for Arm64 like we do for x64 and i666?

**Comment by ds-sloth** [comment]
What "normal binaries" are you referring to? Do you prefer static builds from various Ubuntu versions to AppImages? (If so, why? I was considering dropping most of the Ubuntu builds and just keeping AppImages built against the oldest Ubuntu we support.)

**Comment by coreybruce** [comment]
> What "normal binaries" are you referring to? Do you prefer static builds from various Ubuntu versions to AppImages? (If so, why? I was considering dropping most of the Ubuntu builds and just keeping AppImages built against the oldest Ubuntu we support.)

Oh please don't, it's very convenient to use the already compiled binaries for my AUR package or other distros to use it to redistribute it

**Comment by ds-sloth** [comment]
> it's very convenient to use the already compiled binaries for my AUR package

Which Ubuntu base system do you use? Again I'm open to whatever will be the easiest for users. I had thought that AppImage would basically act like a reliable static build but if you're finding that our Ubuntu static builds are portable on their own, we could just use those (and possibly advertise them differently).

**Comment by Wohlstand** [comment]
Recently I had very similar error on macOS ARM64 locally, and I tweaked it many times to fix that build. Actually, this file is very weird, and it isn't compatible with a wide number of environments.

**Comment by coreybruce** [comment]
> > it's very convenient to use the already compiled binaries for my AUR package
> 
> Which Ubuntu base system do you use? Again I'm open to whatever will be the easiest for users. I had thought that AppImage would basically act like a reliable static build but if you're finding that our Ubuntu static builds are portable on their own, we could just use those (and possibly advertise them differently).

I'm not using a ubuntu based system, I'm on Manjaro which is a Arch based distro.

I noticed that if I extract the deb or appimage into a folder the application works fine but as soon as I move it into a system directory by packaging it with makepkg I run into that issue which is very odd. I do agree that the file is very weird and not compatible with other environments when it should especially when it comes to Linux systems.

**Comment by ds-sloth** [comment]
That's good to know. But, my apologies, my intended question was actually about which build you were using.

I believe you downloaded a static build that was build against some Ubuntu base system. Which one?

**Comment by coreybruce** [comment]
Sorry for the confusion I changed my reply as it wasn't relevant to this issue post, I built it from the source following the documentation. :)

**Comment by ds-sloth** [comment]
Right. Okay, I'm glad that you are able to run the static builds on your machine, and it's also good to know why you want to build from source. Are you fine to close this issue now?

**Comment by coreybruce** [comment]
Yep we can close this issue now, I assume that patch to the makefile will be applied to allow building for Arm64 in the futue.

Thanks so much for  the support!
