### ISSUE TITLE
symlinked system binary does not look for game files in the folder it's in

### ISSUE THREAD

**Issue by coreybruce** [TheXTech/TheXTech#856]
### Describe the issue

Hey I just noticed that when the binary is symlinked  from lets say /usr/bin and used for another package by simlinking it to the game folder it won't look for the game files for SMBX for example but will instead look for the files in /usr/bin which isn't  how the binary should work. It should look in the folder it's running from or in specific folder location like in .config or .local but for this binary it should just look in the folder it's running from even if it's symlinked.

### A type of bug

Native bug

### Does this issue happens always or randomly?

Always happens

### Version

1.3.6.6 and earlier

**Comment by ds-sloth** [comment]
v1.3.6.6 does look in a specific location (~/.PGE_Project/thextech). And v1.3.7 will have a search path that includes .local/share/TheXTech/assets and /usr/games/TheXTech (as well as a fallback to the old path).

But you're right that the game defines its "application directory" as the physical location of the binary. I'm not certain whether this is undesirable or not.

**Comment by coreybruce** [comment]
> v1.3.6.6 does look in a specific location (~/.PGE_Project/thextech). And v1.3.7 will have a search path that includes .local/share/TheXTech/assets and /usr/games/TheXTech (as well as a fallback to the old path).
> 
> But you're right that the game defines its "application directory" as the physical location of the binary. I'm not certain whether this is undesirable or not.

Would ~/.PGE_Project/thextech or /usr/games/TheXTech be viable if you have multiple games smbx and adventures of demo? for example with my smbx-assets or adventuresofdemo-assets packages I have them install the files to /usr/share/games/ and in smbx-assets or adventuresofdemo-assets respectively. Will it know the difference between what game you are wanting to play/run and not cause any confusion? 

For system packages it should also look for the files of where it run as this engine powers multiple games and I think think you would want to over complicate the process especially for packagers.

**Comment by Wohlstand** [comment]
If you want to run different games with the same executable, make desktop files or shell scripts that specifying the assets path by -c argument and user directory by -u argument.

**Comment by Wohlstand** [comment]
Next version of engine (1.3.7) will work differently, and as ds-sloth explains, you will need to just run the same executable to select one of games from the menu.

**Comment by ds-sloth** [comment]
We are aware of the fact that TheXTech can be played with multiple asset packs, and v1.3.7 incorporates a lot of work to make this smoother.

In v1.3.7 you can install asset packs user-side (eg, `~/.local/share/TheXTech/assets/smbx`) or system-side (eg, `/usr/share/games/TheXTech/assets/aod`). Afterwards, you can launch the engine with a preferred asset pack using `thextech -c smbx`, and our example DEB package for SMBX does this in its shortcut.

v1.3.7 also separates your game saves and other user content between asset packs, even while using a single userdata directory. Earlier versions run a very small risk of data collisions if episodes for different asset packs have the same name.

As Wohlstand says v1.3.6.6 can be controlled by specifying the assets and user directories per shortcut. In v1.3.6.6, `-c` can only take a directory. In v1.3.7 it can take either a directory or an asset pack ID.

**Comment by ds-sloth** [comment]
(I'm happy to provide guidance on this issue, but is there any action necessary on our side?)

**Comment by coreybruce** [comment]
Ah ok I get it, I'll have to make the adjustments on my launch script accordingly :) 

https://gitlab.com/linuxbombay/adventuresofdemo
https://gitlab.com/linuxbombay/smbx

so on the launch part of the script I change the path to ```~/.local/share/TheXTech/assets/smbx or aod and I would  would do ```thextech -c smbx``` or ```aod``` to do it correctly is that right?

**Comment by ds-sloth** [comment]
Those should work in an upcoming version, but for now, you are working with the v1.3.6.x branch, correct?

In that case, you should specify `/usr/bin/thextech -c /usr/games/thextech/assets/smbx/` for now, and possibly specify a user directory (eg, `-u ~/.thextech-smbx/`) if you want your current package to put SMBX and AoD userdata in different locations.

**Comment by coreybruce** [comment]
Ok so the current command with the arguments is this ```$binary -c /usr/share/games/SMBX-assets/ -u /home/$USER/.config/smbx/``` but I will update the paths on my packages to the official locations  and use/usr/games/thextech/assets/ instead so there is package parody  :smile:

**Comment by ds-sloth** [comment]
Great. Feel free to close the issue if you're ready, or ask follow-ups if you like!
