### ISSUE TITLE
battle levels creation should be disabled if disabling battle game mode...

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#870]
如题 (Ru Ti)

**Comment by ds-sloth** [comment]
This should be fixed now. Please let me know if so!

**Comment by LoveBodhi** [comment]
![Scr_2024-12-16_00-32-31](https://github.com/user-attachments/assets/c62da268-5f1b-4eb4-ab68-870d44133e90)

OK Fixed now.
