### ISSUE TITLE
Fail to replicate vanilla bug: pending event overwrite

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#874]
In SMBX 1.3, if two events trigger in the same frame, they might overwrite a different pending event.

This bug depended on the VB6 For loop behavior and it has not been replicated in any version of TheXTech until now.

This issue exists to track the bug and my fix for it.

As a side note: this logic difference also caused an inaccuracy where events that triggered the same frame in SMBX 1.3 might trigger in different frames in TheXTech. This is also fixed.

Old TheXTech behavior
<img src="https://github.com/user-attachments/assets/0fb70329-fa3d-439c-9a89-e038877ba36d" width="400" height="300">

New TheXTech behavior (Mode 1/2)
<img src="https://github.com/user-attachments/assets/83f59430-11e9-4b10-bb29-e3f8dcb9c3d1" width="400" height="300">

New TheXTech behavior (Mode 3)
<img src="https://github.com/user-attachments/assets/889ad2b0-94a3-41f9-8a22-135fa9a4cea0" width="400" height="300">

I've verified that the new Mode 3 behavior matches the SMBX 1.3 behavior.

Here is the level I am using to test the bug. [event-swap-bug.lvl.zip](https://github.com/user-attachments/files/18214516/event-swap-bug.lvl.zip)

**Comment by 0lhi** [comment]
The new Mode 3 behavior also matches X2 👍

![2024-12-22_00_33_59](https://github.com/user-attachments/assets/4592cdda-60b7-4613-abd0-dec6a36102a0)
