### ISSUE TITLE
[Feature Request] Parallax BG's?

### ISSUE THREAD

**Issue by LoveBodhi** [TheXTech/TheXTech#94]
I wish this engine support Parallax BG's like SMBX2 and PGE......

**Comment by Wohlstand** [comment]
The backporting of PGE Engine's backgrounds sub-system is already planned :fox_face: :+1:

**Comment by LoveBodhi** [comment]
Here is the parameters for Moondust Parallax System
https://wohlsoft.ru/pgewiki/Background_image_Entry_INI_config_(Config_pack)

**Comment by ds-sloth** [comment]
This issue is planned and being tracked in #463
